/**
 * ══════════════════════════════════════════════════════════════
 *  AMERICAN FULL FIGHTING — BONS-EN-CHABLAIS
 *  Cloudflare Worker — sert index.html + API REST D1
 * ══════════════════════════════════════════════════════════════
 */

import INDEX_HTML from './index.html';

// Logo compressé (WebP, ~24 Ko) — servi via la route /logo.webp ci-dessous.
// Remplace l'ancien Logo.jpg (2,6 Mo) hot-linké depuis raw.githubusercontent.com.
const LOGO_WEBP_BASE64 = 'UklGRn5eAABXRUJQVlA4IHJeAABQOAGdASq3AeABPmEskkakIqIhJnMr2IAMCWlu6eNZAl5fGPnFmRU3QE/ij+t/3D+6/2n3sfF/zb+q/2b/C/53+s/+vzH/Mf1P+2/4v+/f2P/0f7T5NsufW/qX/Ffrj+D/sH+K/2394/b/7ufuP+Z/uX7jf5b0J/G/3z/Zf478jfkC/DP47/bP7J+0v9z/c36Tfrv2L7m3U/9R/0P9B7AXsf89/yf90/zf/c/v3xWfIf538yPc77L/6b7j/sA/ov9U/1f+E/e7+8///7N/6HgKfl/+Z+2nwAfzv+2f8n+9/679kfpU/jv+x/if89+4XtH/Nf8F/2/8r/pvkG/lP9U/3P94/z//s/zn///+X3L//n93Pj1+2//+/cr5Pv2G//X+vOAmQTXsC3lWCU+/zj2kObgRek3bqHXFBBkE17At59JfgTj/pll+ejtodPycC/VufMO7Wxj9IJebnjXjBgC3HK6DhKLafxfPtxesLDyXpMph+/4v5X+og50XFPupy9K8g9n5p5MrHrNtpNv9FXzYjB1uWpwVuQhe+TzbA5Jsx908eLFqn21sp/+oJkE1qOpR20A3BTpCZX58a7SvxR9/1b+z0o/kdkxnhhciPVN42es4QtPbkTRmQertnrqrzu1WLLo8Uqykh4zMOJjceEYQDFX6t2CHy6tMD+WDxOO6dXx9B8cWPP6gmFgr5tCkJNUcBO1MLMbYapKGXglu2SKBONIorRZQLtPmeaGMolQfPVSbiF+8ATQS9B0CHQ6uhdy4cbk76aMdBJ5+Qk1HrsExrGnwH0r4u3yR8rxQSJDDrBObE3Kuao0zs6M+TIJrUo6rXe2QBrODlzYPGdmSkxUymbXODprinJFk8+Q7/v+Csr/4sf+hyv2SBbk9iA6XDBdJwsT/wLh1S4tomnlHRetxeYPHeQx5icvbyIuskk2r2BM0xoEoiouU/bNOeCzFSoAWq8YssNz8F99eS2ZawdTTYYv2Ipycoc+4kMO3WNurygsaGXKxaf54fxtyYT9X8DPfP+UHgl9L560pNC0LbQ3lpJxSYfBEO6ubroW2BVAqJY8/M1OJJvNFmJWCXsn/1BMgmvZ4xFBfsS3bRfU7P35pj9SH8WQH21mLgzBdlH6AdIMYxOEhR7M1enOehLgh1pP+k7qa9U26UxS3jQ2QeMA2stVHn9QTIJr15fu795cdm0o6/58z/MDZHDcLOMOCdbJrfojDyo3CpQsyVX4p7E8Ndl8cde57V3/IeipmQo69KP9QRLV8A40VlpoAtP4vnnsnDbI5RZ682wtbPLgZUYR1LCzuTh08KUsOS6CKX3fOR6KJoE77FGL3Byj8ODYRBEh1YBk8oBkwBHmKz39KkKEMVfLUZEvKl1BrWzJeQJRbQnEEyCa9gSZCmUth3Mz8SR5qkJ4MUCVRkpZnGeiBVInmwn9qz/KPUzRgcJ0oypl78DwmVcM73K5DyMFUeiFygIAcNHg6J9THZNMi5MM+nkqu1XxfbqHXEz4SCF/88tgfZO+gPGjYqh8JxGKZqKu/Hp3qg7s2+ZSm1MoyYEg/7ksa2UF+gfiYM4uLD8kIDv9H0oaz0+JR6ajF96hX0GGQFDuPwdqFl93kj2I61qMFN0OuKCBP0oXoHiio4urxzZY1E4b33IkWCVYu72MbUnnVLsrxwMA25JgT3kRh22yRsla0So8Oz4TqdBntbqqKgxJiFzhpibZOuH4Hba1CmMhAcRBP3BH3t+5MT/btnFaB88f6CZUbe9GAFBmnnbRiCZBJUjEOe5I99+oHAx0473cyvWr9yxHN5059K1UKleAum/3vNE0zFtahuwjUKqLaw4bynTKYSeYU79mORlyZAPnnadTBvEIOjNzy9EISLNfwBCsth7Jv+xe1IU/kp1xOSNCicYL4Jv6CgL9a10mlB8s4S5qhqlmdPW1u1+i2WMeVdCnXuuY4e6nxMBF+S2ejf7129+3OHsuP1QrJQ46b3RPsnMlxWYYBTw9LYTeapoUwG0qfPsgSETlYtSEdIL4tcks6fRRIa0LEUtPUaN3QVd6+rAEc/7r+E10pu5rmXli0cMg0RhaTT1/zOVon8hegHgxl17uVsWTi2n8X0dvdsN9CnLSJS6+5L6CFohRFEvUboynUAroed88T1EwZjCBplh7PMzu8gmvYFs3kMUagxtG5PU4D24MsZnJ7GSByijh9gbU0jsv9nyutCg9YDzi6xidcUEGGfgQkodg8K+QOZM5WGl/Id18c0yc86RmxwIXyMuNRuyzfxQNkepNeW3ObL7Ctd1kw/g14i5QUNfFSIYHDtIBqBYJxURRG0P2JeNlKtqI3o+P50tN5O8HjyTWdAsWtkIcM+TUov5LzsW1vhXtoCLBKtl3W6fO2pxpgfsGAiq4jHSnYTQU+x9o9hIn6A/cQlW4wkDWOaMKeV71HtgPvYETv40PzHhxAG1VI/VZ+8nJwvNV2lZScmO1SSl5ZTq2hQyuJrrdAbhJVMfdY+PxLWxWa4uF5o/Yiol6wPDDU2ZKW2V+ES+0QRcWDyjMnIxJGUWgd5ZHKhitE/BASWPU1PlF+hPJrnryyQkPaG9UAjpec9e0DFv7dY8fAyarlpFnAkbRHhclFDwa1kq6n9EmDgoUBDq+ycCHZZVItx0TY4Df7S3bV4NltRNfsCZIPB/XxstzUA3oOEa7kjAQrCR6mA4cqAEamGd/Ce2dU3K0jKDFj+oJkGDPEgsFN/3onwtBarm6E7w97SbuR4v13HQmHil7GUYokNfyYoqnNCOs8to+Y8u/QUpyOrdsmWucK6QOTq2tOK9xKWfeWTQJVqMY+QwB+kSaY2oMf0cD/jyCB+v2RlRp84xwyA3nYCnXbNXMrnydXgkfdR3hMxifXf9qWji7GyCbALRiUGA3KbPWUSn3GLdW9Vh0A0T/t6Kc03zIC97hBCfOHzcJaWixGTqaFwFdYZfueNxACOIDIN1VWUJQp/CB6pshwzjSVbAL+256Z6NA6pyb8juUHmf2cxRhvO5n/C26DrOwY7kqgeIU15BNevUCDLKMGdYTOdQSC5qpyiM4d246wg4Lbg5byJWETNrwmcFOj//OwVOXa3zgym1t80Qb+RXGXfHA+M7q4QqMTRW5alZQoswLc9Jcv6VMMb7bU2f7q/OGSJ+rYhUmpH0/i+fbrOgItj6NxH0nKZZAmAxu24hRWwPrlllD68A6Xuy4iZ5qcLjUL3ynPmmLKVlSRvBw//GsdRv3+sJxrOIf1hkP6a3n9QTIJrz0Z0VVgJyMsNOfiZwperKZPlKySkuUdv8v7BfQv2eegrvUfbqHXFBBkE4aMitV7TydrRd+QFdSpyaNDBnUEyCaiAAD+93YZeZhzAtEIAYDnS8wn3H6ay1yhyPqSvGgZFT9HFZeXFXkvaLE1zr9ZhF4+GsUSV4gPmD4EmBB1zCho3fQQloomv0fW8gV7u/8yp33JEUr5zC20dH0Fw9XShi6RqXwkrTProTZUp0MaXgZiDFqm90lKDSeh1G1LKyquyeg51VtaowcdIODeAjIx640Z4YVGfGlAPKFYUnf/Jjj0b9yc9ja2+TNgXz/0Q4T+dyXeCCmegWY4TMq9w6up39kjrdIta5q4bUmBsbDBLI6YMDXrZllmDg6XnUwlDJKJc1QDH+DVoGCReSEjwDTwUryGO4xmEQSQC03/jcvpSDyE6joHcOKWzu4/J4akgipXrdkbfs5i8NdVB9isniqtxlw6QdwZ1eGZ49k3H7PNs7mVmTmCwrsF4ogH/JsvBlE+/5LcTA7+McL3A6VoVKpO++XOtOZhw5f+iBWfvk8eRsOq4zaZXz5I0eQ21ktaAoiOUxwDhGdt7PYnky4C0le79QWFmUW0ye8efbtENjcGM0sBD+81H/+VP534fDsyxQDnFNjKcf+8Ynefd6xcSdaWYLObVMgaPFQFMNI06rcvos7n3fo40+tl1MGx/qa1AS6e3cBY/cuFlRWijZ0QjXSQzfNEnvNcej53UmGULBALcAkLWJHOdABMc9ivnRvb0nvyYrWGHV9QyAJQqWvPcdhOMosz8nGRoCQonG78QvQ0bfZgTdzU7/Hds7T9UQ3y8iIJEoU0sMQ8SFLN9YMOkfdPNs9AzuHW9BmX/A3xPxWRTQAcuNQGH0JYKP9ph/nyvK2lYjHEUgSKtWPHPnbxr/cF1GW5KfYsGtKUyKQ6MzAONsLlt+G8mPXPFvGfd5o1UqKr+dYyxqU9Z3QJeeUeXxWZftCEF7PVeNedwAhZNEFZOsAt9hf7/NwjeW1ncHk70uoFwAm4DAr1LmoepcJ7mahE223mYYKMdF9mVKfAHWjZs92T4FKqBDvYRfuEy7zQxIKpLp0qy7Qqk1seJRtQYwlSjyUALW5or0ZVQS36+BRSC3bqa0UF8nmNozDxifslt8z7x3x7/IKH0OEOPohH5Cw0BxQ6iKkcRFYZiBD0xFRrVm6oy6ajqAQGxWifM/kINsYHcNx8QViMBP/Nm7GeBrGvVSNXav0Wc2KRjsUpn8c1Yvq0IRhIK5aTf/9yfLgCurPFSDlwbH+b+GF7uh2EuE9hlP4Sb9HNcMgVIOjpamvgxulbeBEr6mGG+t1rHg+jwkZniMR/lcTSx6v7e3JfATzTRhEuRRVeXyEbamyoc/nXpG2Ql6BV3UAQC2t/uV4T5p0ycCnNfzCK9olBI8OyXvk+aqZjPEg8masxkbduUbq6xxlICp1F8lSAuy7sYISJ2pPqPeoZMYkKOCyk3LIbs/ZEiYXe+7s26cr4+bQYi5scX6rA83OSHJzVfBMTKDykgJtoN7mYC0w7nDjXmFd7PUx8/iHb0DhFD88JaUqAabxG7WIjz4NC2hDjOUOQNwK6aEAj/tJsE/JuLDtP7zzzkyA/sJa7xdkEgiZCfcCAWzAv6H+UP8Z1L6T70dBy7O5F2GA9zEFHcv7TiKISX7AoKB2NbQjnEN2QLajvnYdCQXhX6mq3trTDZGAs5iolLccgBbAtlDElzQywe7ttUawnjNvg4pyZNE8dPzASnt27eazfJ1fM65Hx0EX8A/78IlAxpUwQq/HEWc+I3s3Fl5DD7cV4neKepeHXj+3Nd8CX+WN9WKNgG7/bUihECmg3rfbkI59wxHKO5cpbcQAVBQwXgxVdSiySp0coPx6p4qk6avPfOTbEwG/5zexKLDRiILe/+iQ+vDnnsG0rmG/6i/oYxuv+V9RxG+k0dGDOnI2T/Ei4wCYv9UZAt201yEQCgPlOh5r0Nqz1ARTATOnE771sr0MSn9tmg2cLPNwQgHcX/zKaP1pGy1H16M73cw0A4FpcQwj4mXpWq6Fq+2BFZZjNaUMJREFQSp7p/EvQ459vHCZ7zVlLsaa53/ZbOnxvFfnoIsqtWoLumKcoR1j2Wpcq+IvJog25RVvKta/9LmTQdrQHdOcYxvg0ILPqWkO4OI1GNmdjjiIpVumNwEbjUiTnu+avqETQMbZGYsKNU/Vnn/f849Itpoyzad8FPWyGiafTKNNCT9jRVcSHK5Y4+8qXxZMm9/7KrybjoRVbj82S70BV4eCjmCWRvKoQUJ9ns1o3JszofBWq/hE7Z0ph+boJVr3/IqDnrv1sdbLhHgC53isiaqwOkHv2KDrRB603Jxljt+ldgS05MPurWAuJjVqlPvUallsTMa9IGinl6HhpsH0tBnFfIQE0s41gylTrocQk4S2Fvxe8PFLnlrlx5I3VxRscIYEflb2l4gQCSOJTUyVp6C0LCX3Y3roSYjPSdUpGLd5V2a3Kg4nJKV7l6SU9nP7cTfQJd1K1UJpMapBeb41v1n0AEYxNrya9UQ1hfSY1VixgWfcygCGFv/rJDTGHYqrMof1peBQo7AQEGY9TSbm5NW5KJM2yY5rhO71otqf5jQ6rffgvqj64Tdz85dtX9D0mfOkxl/GdWGaPNA92F+ZORPelHYhT6ODGcC/zSw+zjnjNgCV/8bDplvsnjRGD3XFOtOMDyewbjS+N3gJzUDpAX4u6mjipBicPp1PzCq7hfXlvHn8wUa5mL8k/FMpe9rWqbzkBwXJ1/+2Qv4ziuEPV+STjSXypycSHKZo6m/Q8BO/C/sP7nf0OomExmarjOVPc575rL09XZQo0AidUC2VKDLImOvbnHvfY98T+86zFXuflPaOm8+ZpTq/fid1Ww57G0xS6rO8v/mRgR44UoahE7uchjVk/+xNAYl7RoW7rZj1ccm2srKIbxk8LsVKDWz3qusJLGSrarnrFdE7zLqVYPEh9stpQxqmx+SISHnRIiFwXydHgTmQyIbto7HVgcq5mhoFdowy0YJ9d9gEll3+yJOn+yxp1ZJsVHiunBv3WxVkrV8gY+DoJuwvP5CxtaCHcUcUIGFUQIci3xmU/rvj3HhGgTpe0/9GviSoPFAZo+qQ9D80E6zVA5VmWO+Zuv9+Tn3zDuLD+0RKKhRHlcVsyugfiADa1MEdiHy5TV0KOc1c2JMQB8D1AUDtiTAcrlIjdRwOs3OK4EN0ofRsTdXZ9vZVDApxuRih325GHzBuoYmwIAF1UWnGtdFnqQcLx9Qe1+oRGqfD6l38ilZo7oSR9enAZKTBOqyKwMhVgH9XdxbTsoR3Ey7jXfdTAA6XdY6qXQ34aF4ekSfTlPKBqVQyJhY5JkOlB5cdmn6AxoTNWOlgyd7SmEJLMybZZLkrGMbXVms9JooeH+37oafa1yc8bzNXWgqPX9x+WGlnUdn3wmFqHNvLVumzJ27egCtrStF6LCqLHIgUD52Sf0YhwC54n5/vxUQ50Vl5A1b3x51heQPO8Jj17QtngShURM8oV30yNGYLM08GzyHekm5IGRBUYNqT9FvXSvsHj1Mlj4UW4bPtpke3NST+YyKYuI/R8pZTemhi5b84WctVt62iycQwGGX6WzmTMY7+YJQkImpi1EUGRHjfPKiCapl6WCWAzLwUse0P4qd4wON816lsSpctC2m86qTBcAqNzNVd7j/TgWR0q0NsEIW7vBJcvQH/0j+b6GMvpJRMk3VTlqKRdkBFqoUD7XJecMAzWLIe1Yxvfq35sUbaJTc0xxq4zuzVMpVcbiehQ3hmQri1YDSphmFzmuo2vEIfKOOEQ20juV0ZaS9opuISc7rM8WCvv6qJSj4TB3ZxkVDtxenU0wh2tVX589+SO8LeXB5D79jsvldb1HydPeZLxXWJ7/qs9shFG3YpO5S3kPA+GLb20sp1/uzXEVoBOVqMVVg16tTqibPT10V3O+DCIXBp+5Gn7GgyP1MTDZgnNrcZdBTkOmW/KxmDkZAOFrw4WhfqizRAxLgUBJNlZnh/8mJHui+FJYcXq8XxQbllylUz1nvfry4aCAmExOGXxDh99P6wbJd+jnLYgqcrtHQp7MFnrJd6SoJfN4aCYPg6QnurfC9WTYiPjWDZc5OzCLkUAl6zY4XgeKjX/C6BW4tBHc1xL/cX4+0yfeCFTE+bEZ6cu5WnTJJsAM5yy97jsjqlXTNh++298sjzo5X3L6bKLB2WmfB2NE998ec6DzD4MgSs5zrSeX0y7y5YlMgzpDcaR8rOSF9P6F1IYz7fDpK+p863RvoJ+awqBL5S5rvuj8LlZ+gSN664ImEGwKTrjeW4Lt9GWUJ4cRGIQBiRyO8S8slQTQzy/zYnRgE72yzgxhnklDq+RwVcZKfQOXRWer0vkwprtmDr0/+nqfuC+wHTrcbkXksRRpqPeyXEj8/8sslttS5XmJVjWEDX3pCXrmva6KiO2L1KFwIFn3BTplmR98uXD+4eoKjqwrX2T5jJ+kY7dYBN5JudIRP3Sfo4//J5W8QapPgK/aVJF/JSZbIjIli/61YKtZDYbTueDzPcTiXWCSA373k9Gl0yMIlgAhQcvQbJSHfT++k5Ft9DXdkIJNVbB7MVLGaz6Fx38BNA++lr6IsK6yp33fGxB+baXzaA51btyjGacv6t3qhzCUgYDUTD2r6bTw1k3dBbfYly8qujqDyy38TGuZY8mNqCGBEUw03lU91BKxGT/8KXbGd27PibXquYh0z6OmbuKaZYQOl929fWTQlq9roR/4ABVUAsivj8p42Hui/wS5AAkGqSRKSpo72qP3XPE9Wx/DzYz8B+WKWZFoVT1N3AoABbdnfyAOsDLYvw+miFsLXyZ/yUUkvJgZU3XPhs/xWSXK6fw47MTo/79Qf3QPhRKjBrW+LnddbQ/syfYtU7IJ/ozoG91DstiNpijYAl2/VFE/lAit8VrB26H4TYqQQijfkhc5hJgf/Dl9aQzcnnCWV2VRZkk8xD20BcFWalXdtUcGauCRadjgD7VeMrGSQ7ebzp3PZhxgl6kl1NMgml0QT09ZXcm10kPU9LC7S+KJ/BcgGOlAr8Svz4aMa8XwYUapRAmGtfrPC4kuE1FYQ/XvymMuMuoeQv6UZHdendpr6gMJGnDQMNG1lChVGI473NHBfBWSmZYYdRgVa1L8LGRkIly8S4TC8Gb9ylhIveSTg0RQnKDe3hGBVfsdR2HfgyPwC/toMvFHrG2V+BO0dEUMgQXZAAB6ed1980L8gu3zaRNTwXvEDC6bamp9zvIKJCmI5l86xoc5UcT9jbDkWxzrS5bqi+t4IakJ4eC6Nyi8Eg0bx1On5cxYlZUctcqPubFDZjX5qEZW/3n0IDNhmDyAwJ1uDW91jeGvZ1PV9Z0BBUHhmGlXfbtBg/ZOEizb0br39jzfe+If9VIQmuzi4jw5pQQmRvxeCkgr9IUcJ1tHMiBW+MVP4uoCq1dmK2iztdRGi9+l9A/fJuYvv27SQjj4/X6UKNEgcyHhf6UvWeJ1udZWIo12jFkzswvrwZapKGlM7QH1GvFwZHnFZuSGdNj7Ea2B/dSGlUzdELi+wAUgCYt+UIjFTa8XooQv4llgoSsOx1C+wJe3M77rXDphd1o3Mzzfi9fbHHdjLxsEA3yjOt3ThNaVuDfQZ0axykNegmMBT0CdOP0C2r5YmLe+SU+6kxYsUr9Ed4JQuvasIszhADqTzmxsN2O0HCo6XyQ1vZssvnCap7lSVvtdS9dB4yTlFOharoM1bIblqynPH2wO21liQXvh+38FMyx/AEpDv5IY9uNbDsLKKM5oonSRKXojQuey5cDgX+DQggIS5x0jeOn0EKoSCGbtOu789HRPPsfaPEDfd/cvaSe8xWVUeljNLuGRBTUrBnN9PYzfiW+34yk8xm5dZL07+rf42haipKr19J6p+Z5D5zTSHX6ymS15KKdW2Y8d7cCfnbrnnJbCOxU8MZ1mkxBWKmUJkL96medh6HWv2GxkMwWPzEly1KKP88AwMwJo/8gItxVsAj6R+A+Zm2AWtyA8n9hCjdwCch2VPwC5EbrWea2/D8vzgVSCDng8dNe802V5sf2FiJJ4tVGSI2WE0f3waP7mspkmozdloRUOJVEFgDk2/PWhO/EoPkewYrOyxUgodCntvVVte7J6idaRc8OkRHH9hPKduCc5u+fZsMcKhxw06xbsOTDUfykkGB6hyvUuAHEbFOa/FiJwe4cddxQ9dh8HvilJRgBseCAgqvzCIi7xlzgaDVJ1x5BWL4IsFThuPcFKq1EBsuBo1E4YX6LKe9C79Q4usRPxM2ka5xJopovFKF8+2tlmesLtOCn9pyy2E/DPMPh7FoYKWRR6qzgd3g5tsmRLm10vI+IYVAFTG4TcjE3+jaYEUy8SHirxVFb/N7snC03nLu83GFU/zT7C/Q+882890+sXp9acWSQpYVIBkaclkNTcj/6CoK/9jKu//7Lec9E6kpqIxcINmz7/5EwWlvawDRx/MjL3IjwD1HAbDGFKRKei8Cw7fufg+6DxZDh2+XM4O9FwdhpflHf3IgU2MubMWLiWy1jZ6YIsN1T6M+VuEaNySMn+yhqEx9dYji/IBoSBm/j00f7PF0NvptU6PrCAN1+6QZ8gfWem6ePkBt2Ab8WZ9/6ii9NJ8B1ALdmorBfVfzu9L1wF36AGR6yDfopr3JwuwHZESgTYVtVNXWHIP6btB+7DcpJUDCSRCtjT8qr+U1HCxV1q+2NO+WJe2oqXVRPuolyBC3eQdHu9rkwAUD7Rc87IztqIUntgKkyCQ0A40Md5wsHDBDnNAZRbaVhEpkAWT0WRjMN+UYu7YOsLOYtCFD8lRMo66Or/Y2aarm4OzkHPbLVsENyxAR/dwVWT+z5QlwMvk2rE/9Z08J0X+C3XMOJOsybh5nnfDA2h4Y39mexh9+xa3ed4VcNoY1sEESzGlA1gT9LZhsBabVwUZjeT1o5ZvK50zOh7m8fOLHX+dya1OIO2DgOKf8O20xDjOt8bqK+/cbLnxVgK8Kp8cz8W3D7BNUOlhClGwbAeJV6r8xHl05pnnMC2zjY5rDiR+ikOO4SqN0qp5cC5IO3zDTDrKeVE3YadrI5xINmzLsySWkSQlSm0hPFiVugcg3fgB0bfnUFzE/Wp1Qkx1X/0KMgWJbiCeruArXvZKywNGvyEmcC9jUBVM4ymZ3nA4IkcfNQlMVyunYitGG1nucz1JYLw2ttgWOGfxxMthzeGjqu9PcKk5SWaDs8V4mNuEiBp1kV3JgU3RNkGVr2dkdmdGapVNLOUYe1gSFMQktsfpEhxAtvgIn2rEwlPd5Xj0PRlXXSGhQh9lIQ6mz/d38LI6qA/0HCLTGgi/km2FX76+wW/IoCAcmjvn9vTmYWg3t6+3YpkjjSsmfEZVrM1SI0zUHhfZErgBFtrV8HiOMDb2xJwtuAQ3kFvY3XSrdXTQE2VkIs0VQYrlEEH4HhuXN7nAzeoid78PZxZ28Q3+/Ubdw561KTcIoExqmFgjTSHHzZU25TMXcFV05BOwfVDhGqHNOWomKmGeDgzlJECE4Q9KeKpDWgpFH/dgrqOK3QRlrQAKyoZOcmQ/pAfnftD4GkYpRSCJrsEIzoIOwSc+AHgBBg009QmUZ/BbPTmEv4f81DakJwyaTe8CZXMgmI5531sdobuKAgf0/M4i8LM67NYLAI+vBeet9AvX5Jpe0yUcKq5JRZl/t9EJTKmuMpRcnkbVs70yXmMEkC3nK89qVTWftclBNotrDaY08vOtnMuUbqiSzMFY4JDQFmPehv2xm58kiTffj2KQrlpUewhN5Qp9aHr7SyMiLdlJIOzZ3QS7eafdq7ei1058iWry+imQ4qKnZGXs0hfA6kyxFZiVBTiUbmWG9OpXZ5kM+lHGxPnYtS7Ds4dsAYfOEOLkCqh3ZLtWaVrkEJYERfsKk4K3FaGpyreqcefuzHcOQk9k8H0MMqGqFHIi43Mn1LcNp7CvZZ0bPuU/Z17WirEgeF7wTYpkWsokZsp6xc88Y8q80tK9voowCCDNVUoeMZ7vvJlKmAa9CxkhuAEWrNiLGTTBvmnVnNTuyDegDOW18uJOw+vHgQ+aMNr0tyuR3hYgG8fYOvd4FQLu11z1H55dJjfUnxivEauHnJY6VZa2snmcm4XWPFOyEjAlGfnWj6xRzouRjaV4+zanON03ZxiyIqVO1JoOGdro8o8ujhHF7rpM7SGf/QQVRSpdiRqJ2M+7FtnrcG0xqeoIRs5TqFI6RDn9lV3ytROoFCW2ctT9cxq49z+c5XstQZ2OgpR4nIszPQeZWLv06BrzjMM4IcsZgMt+Q20VEJwKrLD8UCNE2PpMXh+Zv6F4Rn839j63H/w7eUk0cAA0GaeBW3ke0PqDoLw8e/l/brPs+AvFyuGwxtdkoCb/bPNTARFz2u4FYFduK9WjWR8Sgkp1MrZSjUVmFBJOkY2D8wiJp0lCsSySs8GRrbuiwgZaoHzbt4a4XuxyyknlmAcKNQkkuwMFBpE+1UjeIyjARsX0Ylpi+U+MzL8C+rxQivgTjQebAB8aKvHtz1PUs4t4yilxLPh61dEEGTzh8tZSRe+GrLR5w+KMc9jz/cgr8u8LeR4BzkfssaiEvsVsJ+fWzYPLzXyh3RkgyxTIuLtZKGZhrbJ1p1m2G+NXMMLTJ8xzeYwKKwgu9UtGlzPGNXSJcAoXKtA2fzsyQu/Z6c34WNO03XWdOo3/qr6sAewQrE6em/57IV2ncFt3w6C6KTDftE1DcJaEZAD440FhNwq4jPnKoSXgrjnflWH4jg2Pa5Jo2VWkcZQh4/FOSQcWvti9eDtdxodPTdDgG2AZQGP+hXK/4Oc2RZY4dLhTrTQVS4sl2JOCYy6C0c4MnIAQlm+3EsYvt0Rc3Zh/+MpXkdQ/VW10p/OFe2gxsXYeodyclneTC7CflHO41/1gOWMV0qW5F9QLKs+x+yx7nYKWSKfZ10BJ9OfJ8dbM2i8R4o8BvL4OE7b7wyNCdOIGhqkqnZVAtKKjSIf86PdggVaZr6B2FpS6LYQXdcXDafq866vf6WYxhZ8xDcgF85UO/JliiTv/q/Keqi2fCEhmbIqbX+9qXQobTHwcVl7QAz7PSZz+itNJn8abs6fkUGB6kFOm8gnJkXDz25L+kpVEslpQwWgX0NbPXT6/7EDX8SEcmAtovtTL+4gUBMegxbOr2oDITka6iXZUfRgmkFHtFwIHuAfp+5pky5n56s6wDMY35VxDEFR8tAs6d2j9YvwfF75IxgyDY2Epo72ds2ZMdKugONXpsmJFZ/LZFjQhC3CgkyQgpDuTrYOhv7r1FuP6don5qXbWBgtGHRy5HFdLuj8B4CFOqiVk5/NQfD4l+I/G+86n3IhLoLr+SwRxoUOB56eekfKtYp+h1aC5DyR8oi9/1f70Ks5r2QLfR5gnMMrDz15VmOvfI+TSb1zTPihGKEXF9S8LzVTi0X8xRYmwQun77NYCGy0ksaHaYVjMdmWf+SCN/VlJNF55r7GfiAst90CFq1QR+/KK3JR0CAHoikL4osDEhgXOiILZojaK5wFcuUNgzINJ8LD3EwuYPGUDuuYPc9xfrVYCLM36kKcP2aTZv4RO4AMaVeSOiCqfRog19WIteJOa7glxegSF0I8xSSco8+O9f8DQijKVdQrK+W0NyZu6xIom56u0pVX+X/Qp5fnTjAH5XJyuRxn5uwOB04VoRZDnH3XjKY/d1JNsEgyrYcV/b6jN/kqwFJRSEAxUQAhvgxSwbx60P2ixYFkZ8FfYKlYLjnArEUzoMiBWQTKdoGSl5hCX4OsrySYcbF7y3abDhlHpoQoAbbkI/7nBfZ6puKZir1LXBnOqnZ9OImUXO7+VjurE9B57FBPdM/6UxjNbpkZpRA2DMnJ4Ypc4ImQMdnMMRhC62yJp3KwHWBALjrH0+4P0LZ/lnLxRaOYVbGewkViMnDZK22rdZoFGciOM6ZnOtpN9uA7LV4XmIkgvuxZMRjmyhz11pWF3A/wOYojBcBlhrZg/Sz9IZAazMa2qvaf/jC9mKkOrQzqolbGUHIrk4EqXWR6jDm10FCszcF7g0tVdnvHTMjkRDgwtm7601sDvQbPbVgIgeFXQeEqzaZ2FbWbo3hgx2ARhJTLeRWtLqyRnF1ewismpeWpoC7gJnPjPKLvmqvhMq62b5z7tVGllmiHmcYUnV/e8Xp+fmAi/LRHeH9AEbhjzuAM35yw/OmqEV9iunQSysNVfAzHB1wwdSn/0nVSJBD4FfiHdTX6fgTs1aQ/Wnh/o5eMNgy7NRljPmP2DU6V7MP6VBYIGYJiPi4E99mMBI8gGm0TZn2SDWHDmWgyVPjmBzF4SSMu/UE4oe6R6rmcxWj9D+XIsVZYlhrINwhvo2jn7VBSXADEF3RnrAlh+P4DX6BkNbcYApvC1AKeCyZYgC3ZsacYvgSB6Y01WQAehV+X30trn2aXRTXfntaq9QIxBR9MVF4X6p4JZvoVZ4oOG5WvtUnDrMhS1ekngiR7MKT0s1MsPj8KfxPrAZoc7AFVPPcE8gc3meTtzlPBkTFSB47aF/qHzRFnI9nEsuE7fg36NGquz4jH/yUz6BK8Pn3vY2U2myIaV5jKp33EZHR+NRDIUeWD2oVD9FBsaM/PEkEsaFVIE5X0KTLk+i2lMlfadr3CNO9EriYZcTzEywthhsk5VNKqucgU9haeBfzG/+/u/Svc4HF45+vFQ3FlnMqauFS+yOBVYXGeC5zzVuixKTCx1A8DQFb3PKXu4r7igs5myG7wOv0v8DX3ikepfRfSUREtFZRmsIBY9k9jTAFWXYOb6UumKG/yOTMpfgHywzwR8TG9k+H0EtlNmxPQ37ArvMb6MT4U2lzrlowktY+IV6IyDJno5i89LX2Z2mq4jsvI/u0cgee3rP4EtUZNJUbljQnmwBr+ufnWd2ZwXuQVYjDihcnfiBxl7zW6KZFZYbVWFeGxXaCvFvT4WcmxnueP2dySjTwK2ntI8HT7dLncAGFKO3NO73PaTs1O1vzkp//q+zmonq1q1s3UdJZU9fBmm3S5VcPfkOlmDM02B6WJR3h880/0P7B6CzcpXBDslHPx5XnOj48Z6b+ONxvRiTCNqp71/pYMuR2zvPVKQSuD8ZHmhSwmsSj0/b3DphWicxTHcQySuwJQe1qzQfWWZAmQ940cu/QnFm1AVzu0rMHt11hrZPPlS7vUKo3mRueFWxu5n0K8S9kNHoGosPh2EmEZhV5bl7/W7XMovrYqUSMCKAqvhy0dM4dnMW8v5iMPV0O1II19t9SPHG3Q8DluENqOkiKi5axGfE06vfSMGANlCrJ7KrBlSHne88gtuMc5DaHc+gn8yneQnClxWG9I6+HnhjigKG7VMVSXGdLg14m0GFYmnQJsbD96A06X5R2qW5c8vxFejGPvg7icob1H07YJ9D3NW5Gr2JIuDc/FrAVVCEPDKMKSnRkR/VltCJrXDs78/dmUOgO/it+ZFh386CeEZHGQJ1xoeFWpB+BYGGK8eiBexgZIpOA9R1QFFF7rLmzTj4T78c6pSbAgmbUnafhGTRCD7bc+8jEwfcCu/x4AozXFXzGr3Kc7cxldPEWIJFlVCDQCg1H0CS5L4y3A5rWaleZCv9MGCcmb4hWdGrbfpuiEpeYe17m8X7EcpB2E3IQJtOEB4/3AuuqaV8P272vy+plOZi4BnByat1UsHTRAhM4q8WTwzISNhMnO9D7ao+1riDmIMs8pYP84tzEv7949P3TZXw3le62pn5Ikw1JbNz8FeA6+7cjyA8sB4nSKRVHbHpRUE0zZnDCqEikGN8vizp1cjL21NNA/waS963koIDofQNdoHoH3we2dNGs7euVXl0s2pLEUcmvBfDvFjFO6G3u1Sz6eUNzc7OJvP3+OFmkWLzlHb/P4VDGWeZpVuOtmJOFmgjIG1621Maob4QHcq8q/FFqj/nFMR31P56hi7zPD5GMlWgYOniCiitdTLdSD/Lo0UUWCvGgKd2rB5H5HldvlACJIDIWoZFlCh/bSGiSq5vEYCKyHmNODS/dmvw1SvQipOVUw2ODSIi97c3tbJcJ0vr1WfSKGHM9h2EDxMsqzmCr/ZfMguQKVN+/+7T7yL/Z3B9kRKob03a34Zqwuu845aeGoTtXHb90eLVHmwLO+cBcs5VMAx4MKLM3pqyhmupMkbb3FdJuKMpxKlofcdK9TQqVhSTiJdM+BPGS7YBa8PofcIQAE010frlt3R5DmZvbVYBpBsxQ75+S5lOKSOGifwtnTGwY0DnmWpm3rD/8ig8661s3lbGVjb74x9PvZw3XPPukikG8o8bK+r7lhsLOi06gsGs5SHucNlfnFy6lQc8biEAzfpi2pqdmzv+P7sRB9a/I4cS/5ngG7xHeq4zcirm5VM1zHfqXYiASvyb3g6nSwmehLh08nizziVHFbT0zjQzwYnpjI6gdq58pmE0mN2yUtzd2312M2WmSyPlZ62bfaCaFx4CE/idnewxa6KseW/eCqoeGlzVgfYUfO0IxicP+PWcWi/9iwCX/BHM3PS/LgheJ51qHwtvikv1w2/iL1G7WYXs18fWvMbECfZb1B/plAAn/lZiBI/QBkBYubIs0eKg4z1XrcJgnUXpNq3XRUZnupsiPzL5A7Bv/zRMOqmrTo4RoGtw3xYLc12cROq1ue197K0fgGT9wZ24Q19sX7M9soxHnCikqP5P5rYPS82fsYM+HupoPdk9k9V8VnqIjwQnURLHwN0tG9idMavCfu/TWevvYZtLt7rzAklaVRPCHt5kKWwi1xaOnl/xJksHcKpWlxfBwoW1t5e2Nq03UB9kmIfNZ69HNTzg4mAwQ0PpcXumDy2uoODFSqQuhAyZvGkdHS1rT1TEAPq8oxLTgaOSKStIPshS1/nWvSkY5vsKgDRFUC8h7wZG/C2oUwKMN3owF7BSLBZVxjd9qpRA2tYngEgwr50z1/9aD6SW5EQeaQCHrA3uRgWvch9ipsELJ7WxmeZAk/aNR2JjP1ciZ5AR9udJFM6D7qESrNq0c77jIoWeeIlOlXkstdyt3ZJ/0UtTpuMmNKl+W9t459zIXpQzy3AFxPDPbsqwU3Q6Y0y1Teqqc+jUPHVZY6apjkEZCJ6bx+GpiDfAOqH+P6Dpa1oiz4lLh4vCh9yLrVXLN/WuH2T033krz6CEu5CG4XO4HZtamwO5a+A1ncSqSAjATFDhhskxILR61r4jv1/HjD2q00QFw415lWO0HpxtWH6AovujXGHUGvVs6rbGheBukeJqqiledzrLc0enDX7cWTt7NCNXI5orSGoI4bDawzsGb29fqxw1FId51SJu8b38s5CketIEv7ebeaLFnmCWgAzOTYBlykKgehXLwVA6uuo1cfAz8rRXs6uKkeO+wj6AM8+iybtImtUYAxm/DmUKCIbmzVpLwYobyhnLsSuPKHw/T7TsmEwWMWxw88lPcf0n6KhmLGWgAjyygYzUFZ+2KNlLGVRPYikhTJMJ7B9DqYNya6jsxEzktrbnU5LYitLUFIjIcypZklzNHTMhh9mpogyovWdBu7zHoseb+ZO83InQHyoIDFNW3SgQe7GvqDzKS4MAbMVbfztDX7Cp3IMIVrxtTn/gu8Q5qO90QWT829Otsl56ghNGaI2If4K2n4LBHwbPYlU8ZJz2s+cGCNkEDWmLhKnmDJGT0ULz9rdFsUcfeQVqr6NDXlaqyPoSHQUq+SIg5SDXAwpdJL+k/QkzD2RGe7QXakBe76qHm+6SV+Clyrmasv1FgzFoQWdI32t9Tr4CVW1xZw1IZ+eS/zriMaPYWuAWIRErojpneI4yVGFMJFvgH/ltphVR39RqFGvgQvrByi1FTjWHFkWmdumqqmLM4MAaC4nVdCOAvXuZ8SZW3XKeNalF9Mp7Unku6coVuaKfJxNYsq4GfvieWGH8r7EAN/Cr96Yrdlv/wbnzgDn7LTaPWVecJPtRQBhM4oRXrFmVglnZ/N9YMMawBGyC4n+FbPA+bxKyTo3IJLY3PNffeD9daMg+1EIxOrIY9iX8GsScPp5Vo6k2OtdPWxWNctFf0n2MaeuY+5ahi2XRab0VE4Ygl1jQ7mBKMAD8pG/cLw0bJOyho9K9FhStfISINm0afpkSgavsNXoGMzeCzWXR0mVu4iiCl9E7vCvP23LvYvQcshpYMpD1OR8RDSvyAz7BO4oVV+Xtyg52yQ++vJmtjCbDMePK0G/R0rS1WCNsDbo4NQPxSH0Hew9ZEOi8WFD9c3BjvtW5BBlPl+YFwOw7aTsf5TalaMwlhcmBY1jWhp2slcVGfbKux9eVOiPpzwpUOF63YCtukUID413PYFwAzJnSKkraEIsofRLG6qag54kv/w04mOCxZLBT1/lRWKQ6lzfvp3Ml+R+w9CihrkyrDlNXk2IFzOBIVxODf7pjSWf7DdkUjKucMa5D8C+5Id3dUcPM2W4cxdO2McV+fZAVqhpxf1FwmI/+jtSV/EnhruSLPNfv2Q03Phm2FPUz5nmojJ0JmkmQcsL9Ss1G/gGe/K5Y/XoIf/0qv91Uz297EZrjn9nCjYr3F2JrgCBoe6+9x3mzdgqPOEBkhqwxTfqi3c0fQpaqNsTsHUrsYKmgt2A+Aco1YpyLmXRQoPWmi1MTqjMHSI9kvf3AXR2o0QMcYz2wj5mX/UCngoYEV/WPbCwimAoJv8xAUPhvpAfmfi64pSfprtf92SvPT9+2yCvU/pVYL9cM2JfTEjlY5vrjykU/OWKYqI6KgXLrSWNt4Pn0WowKTqJ9jYKkDl0ipFjEFv41A8mcX7niCBqcCCU0rk5Ybl6n6QvLmzE+DP2kVQxgwViJPi0izBYPoCwbQbyPfkxlfeJCJJ03P9nKchYT35Yax/EAu5rERtwRyp2EWFDTJ4Zhc8BPem3HRsT2zVf2Twy0mrww+V8o25cpHk2fOJOsjZyMFklmPF9SQtXCn2RjzmaulpPwldyLN9CBbTysm0KZKDk7jWcuRmmuwoVe8px4xp2p4rSXTeoPVNWfFGuXWqprZ/Sl0tkuH2IIrECsWdBUdZPJ0irRuKbuUKQNw9egSHE7DuTnRnFxmrRn+U8jZxiX3A4sRnv5/Hib/FlghAmlernVOYcjRfdlHMc5qOIuBbGCWpXsKyPUpYgjPU+ZqqWjU16oa77Ddv39dBQSKnl1upA/7Sk2dzlE1U/xNi/aPtZ6Yto+XxsB71+ZIrMemoh7ikpiTBJLqyQXotfm8FJtuEYxrcroP70MnviJJhOJ90gsJEd02xTG4n6L/KwjvhACtnS3w2xrQ/sBa6kn1JPeDOkucVnx7gw+5gfuuMSqpQ+nrbnA4KrAk38EiMxZG0eWffFXdrcZdhUoesb08b1ZcIl5+7GZR30c5eaDcoCIF0NJn9wYupTFR+yZfKoMTg4XeQEQxt6ZKi+z/MhExRlsZ3cQBqwjH4wEdy7a6JRW40BrmfIA7RaIefE6FPIlxoXdOR6wrn/cQnnfP/th1dodWZEYTkUiYdgnQ/C45+jFpSAg3dHoDJ9r2/h0cI6mioxbZsrizXjIjCbA1OVND/SKFd2fwirTzLWDAz6mv2kDvOHWXDbFXIPuDvIV2N+kqM2TLrJkcVDD8pW07OluVKs/Wh9HUPw2TmZsUvP1dZjI28dvdOfNSJRMhi6XSQWXrHwLWmVXvjXHbnlAOV1P//DdLhoeJEeCxM5+xXrg2LkwvW0v2SbuK441YWVYqt7MWDeMx+hKGkzLxiJ8VVIbjHSwL791KtgZbeO5UWCK21d0psIRA3dDRZJ6qbv3qL0o1pih4GJwfyao/7e2cYEb3l0gwPoEM2ObWLOlxccSgmtTtkN8sqT/Ct4qIdvuLPpofcFBGBoCUmU7Anj9lPTXfd/ahjJsa90haGEN7n9pfJDLnsZRvhth1Y2wencrsU6FEPRqGhyDeom5j3N9gw+2KraNL+bxE1ZBiUymaXQ89sN/Aj7jvcq6YRxrKhDk2jFNa+sYi9zB74rfhBrmxLCnLhMMuyLbdUd/xVrNeLpfVlu012XvZgovWQV8KL2veaFm6mIPxiqqVpg/yGNv+i31ROe6X3QBePbpehj9Z5AKTw3FBT/OP17HhQNRE+e/kNui/lds1ZLue2EG6RyPeYjg5nIZ6UIfSHMGXBi5Z+BB2QncD1HkVymrUzIl5siM8nQUJNubc/6rFBDY1ASN/4/G0tL2lS7WjCLdfYq6HldiqMcaWL7VEds0wostBD1pV+IKZYXGp4g0Xmkm99mJ3dF34qgNtpY59AxNplnoa5j1YK59sIi/w3TB+zviG8fylaiQ58S3eGzAkqzT80P6w9WFyEAcBwiN3oqjrjI9k0HIvfqmd5Fd5LhIzBhT9qxgMopPBsZJITz3pyO4p5Q2Jn4EnZNnz4Sz2OGKuqANmEhqQaLbVz5SEELYK7cufp6OwFoerREAS+2nxSDFwiamVkFRdIk0oHehPME6Mw428OGDUk/7SIFb1ro0RD7PZOGumBKYcjpAz02H2uA8gtDngoW69nFNIBYtFZbOQtQrUuQp7FTNuaBrXoSx8FwgxFuZhGeuebfAek/7AokL5NwHfzPsSvI7/Dxh/T3BdcqcfkSZ9SLeUI9S5XxrM5cluJ5rvQ9DeUeo3K/q+Ea5kIfDgBB/bawK70DcWxQ/+eyfgTj+8iaDf5oau1h8wY1FhvzlMuVthOPeYP7BVZJgThf+4OGxuvBww12M4/gJ6Ut6BtcdeA+Jv+mdV2YdDVIVbCM0J2/Lkfp1TcbRoO86yBGrRU1TQW7Gu089bPQOUPKsh8XD1zMHKrKt+14lJ+bFb/9OhZz2miSSEhn8DFNp6u243SoeZI9W8uSd8jbMh4WEJ0B2i3ePtQE/rBO+oK1oAd/hW78TwiygJudVslSyRFAPin6PasPIULtb1E4bJTpDFj3++LVdEEX+uImpPtL2t4pd1bTDA1RKKzbuJH+EnbBXwT+8lD0xSAlwpyl0fAiy/oYbp7DHDFQSC5A9Mde43t6Lp/OXl+rYrI4VJR4L9Ra7gt0OHhfaLVlsTT6qXktGjG4urXPQGqgC1GvMB4w4HmR3lsNLMT8o9UervI1U9awE/yEj0ofT03i9EPST5H7QDHBUnr+jR2zG7yarqVbr26jHqpKtgXnY47A/V7MdXMNV93Rduw3+T0zcb4g4LyvkupAjTTdVm884llN8JR/LazhvRQNOMlR+wd9w3jI1306x0w/2zakWTxXpHBzscNjj94Jp8IDrYp9qCAAjXrK7yMEjMbbQgGBl4aD7ixLQn8lDPnL2un5aUQL9h4mUEoLITee++h9U8FFrF/sUgl/qcAJKtWEJCNB2qoXX3dbrY6velvZx3iwPGlMr9NvJdaUDLFY0t4LcYQ6JeYA0eFoYUIIfhh4iIu/xJwBll/CQqyE3JPLHi1F0Ks86IRNSiQs3qtElstegVPMASVGZ/brRO/c5ye7UwfbNr2ue4i6rBtx/B51QHwBAfYffdg6xxliOSuVMfXHoJxSGmKJuuapfW8etLvDgWlPEsuj5PxNOzKlD8R4G6nlc0IL8yZLxYBg3mrEmJrxuffax973ooAsI5VdKdymFk2YbPcgiGR7e0NdEfGyafub9jo1W5lLVoekq/aK9I1p/ok1bxNYrDp6ckU0BYrfQV7T4omrkwuNPKdbGpSWhSwJ5I39T+uZs3ZJiLPA69YG8FDg3kklJDzBqGLOGnOAjSl/OtFSrEeq8963bqB55E6K8vtBbxKamXeHJ6OBSFmkztoamtJTy5hwoPb8lTxlk8Lbvj/MME1Mu4GsoG3xzDoKZ8VUN1Ls4x7O1DkMUDzOr6sI7c+ZD/dgOasNVX08FJTdGtf9RX/YNLn60+mDYbhnGVJGEsmUtQLBbDiDi4AqdtiL63fusQue7t1t04xB7C+ETNkyTlIeRUKXxd4J0sHRObgu9QiSlo44RgV/zztBpVpLpCEGXMtrfW3YyBGSeF34VFBq3HzfT94fKH43TVbQCOVzp3M5GR2Ujo+HJReF/zmMfMvLj0AGHZIF8N9kkCcpSricY6BeLaeUAVhF4Ja1qQxbeX3C9nJRdVIFPjY/w04ec3LDrjitniTdIFzxsDMMs61IlVn2YyDXesHtG0TDGUoA54ToFDkRD+AxZsZAxFCL3ZX6An9IY2JUZ0sCj5j9HFD+MNunMVMNpqkR5k/8jeTHvl5SteEQgXD/Or49CtYTN7dAXRKn/IycQnUCLyyCwJ6McLazNgDdJvFXiyr7vYD1TvZn6CpbYWLCQwgyO4vTAxZ+OBGpOhkRKav5rXHhLEwjquRQA/XOx8nE9YlantDjlG2a/sfVA52r4sLR5ueBwUJtEg8ustii+fadX3hXN1mSxl9qdsLb2RhZXw0pX0e7448MNVUu+xaQFZM5JSRXOvTXZiMabJK1GiiTyX9i+cHjQMsH0HLkwWYTBmJovnVysJAehLDu1vfUFQpC2trrhvRNqVWXpXWe7sie66lyttTxNE6kAzA6/McymtLtZqud36kNPVEY1Bv1R18OdqxO8nErSsSzC4FkA1C8Gl06d7P/JK49s7EAMn6XT9C11kQz0YaUF6/V9D42UBYgNgnySQtKGDdeBiJ48EZ1JKx9/9+Usegl/PUhRA2ME0jqiE4w1cJ9Rj8sME0RSBTk1oH3UBChsncT4KvjvDq4wnqT/uCnSK6gcja/HNp03JNhm5Tj5xTId30fYDEYHDr2UeiCwtbQc5RIe1zuCnq3j9m27uLy7sc5cgyIQs4dDDbOXpzlV8olsVtRTvqh6GqW/28FzM/PrJ9tB3EcHSQyRk4RKt2kd2kIFsQ+khf5TjUMuMfbgcA1OwwEcG6BbmpzB1gU2zEvQSW0M8ihWUBFhtkWrxcFIU7JwcXfraeovUu7lz4JAbftzW8WNEldg/Q4K3ie1MilGgHhXvJd082IlRQMhXlT8mKyjB3Oqc5Uy0uoKixsuwOC+kuDHXrgttI11viqGpDpn/tr7YmOGyvKEike6v84SQcASv7N8wGzkHsPQ8o5suL2cCxZTkRoVvCM/TcCdn2mk64VlQ1cSP0MsWs+Z0tIkQu49OmLsub393R0ZDrD1yy6EW/R6Z7FUkbjjwnUU+cL9QyfSPk+VF/cdizPJcIOpXpotC3Bd1uPMvIfL9MnS8uMQEfSoAGB/1QNy+grl515fDBUUiMA1JHYHZ1voTaOIZOVMJ1mMfjV9xvm+ACtwMxkBIg7WWsRK8XCtAaQQTsiPdJqmgMb785gX2k1OYwIW1BwixY26fX/pvYdADxRPgdU2PbuekhWAwrC+qGOyuQGqTvo9BKEWaktvufhCMmCfZ8Uqgo4bP86HYuAbwXPVDnOmamvPZgN1125AG4dApnpQBoGzKWmHMB369FV4v0WVolWquZNply1vxidtej778HuJEPMaNbdzQGu+L+nHVmMBmvK2ywORH44itvbMNVndfAdlBdE6VzR91inZpUNCuDuFDLqeflgC5M3Nq1eKFt3xgVQgjBXPE3VNMKlaiCIDVBk+7XkOMPHxp4jHylqmFpI/C8zHcWwnxPyH4xXc2Lcc4CoiI0+fBVnDxD1Kb17bgQSukDDSOfWHReEXQvz8fWLgspeYfGMgSh34TQDIzLrJlX4VnciGSLHLmcdl0YOnE1JNuu3AFgShaRABGWe9fpYplIBQ/rHH7H2uX48sN96HyLH0Wk+e/XpCRWQuUbFiYyT1L0Ntxg2SUV7bfW7+6NqUeaBhQXEt6HVGtqnYvishIsDH9WX3j7lSRniXPUzlVV4Myx6/IaBX4AZQwfgo5lXV6FMVdnJUJRsC/AVolfnt1IM4m9F1zHKkrVlyEGnM1ABVV+BeikP34dMEXowqey2YBSQr4nRj7/HkPmo4gcbezwmjdKb8AsTt6oN74oqfT2vsqEJ/k1gdH6aleGSej0ntnI4t7/rg2/rrnpkt4N98es448P4AN0Wbw0yX+Qp3/yWSfd2UzGjQz5f0Ad0iOl4FhBe+eooiZV94hc124u4dhnpU9quPpBdhWr7/cljgrrdfGynf+peWqyC1EjDm41vHMH9WpwEsMaNER7HmjwlUADm4xp2DQm7eFBKhQsearob5e9gphffg+HTh2gexOj4c8Vvfje0+Igrc9XumYKOUDwmJX75gaMuqAL72CQud8XoBCPFkUu8EIuhcNAN/NvZgm21wt61hec6koYZD90tRhVtDrRiK8IPobmvfg3cYMhakpe8bGhwnGv14vKn+Sh6b0Hx+IJ9Klq+ENdW/W/sZ7ZxgpYWW7nkeWdd+JePZofb+YBXAhL8v9tYOJa7ThAV6LGCLVfDE/yJ444Eeb8/GMR1tr5FAYNg1N2GRTBdG5/pv4NmtwNwLwzn4zWAugfrhAGxQbnYoaJOJJtj8WlME8TNg9uaa8m+Z+4/niy0C+NrmRFVlVNco4k0WFJXJbi75sXYayNmfrsABSPHza43qBTCpUlj3DJN1V8uHOyLq+ZdBMqZAErzaJK4id0wF7b5KjO4IHKMeyJ0ytun3XnXydrPki7WtwPVUvz/JZUvDRbI78L2P9ZgHimVkIafCxNNWaRm7PwFMgzaIOdUDow0af0QqVNG3URH3Yi4SQvY3C7h4Mwejzs+v38zAIcyS6ZeWH9MuHMXFb2waGFjeW0HhZL8So2wt7MrYeJGCSDK/BGqGil/wqj//2BWYAowx7Ny5rvdPZ601xS7HU3DbrpeAn9znp9Sj1/g5h5uPy/lwWvRKG2qjNbAoIq/5nE6ljgY4A6jz8ixsMHQqPdI9yVGYMODaKU5DId1IFYFuQEntTwe3lv2ii3KDtUW1eHgh1R4o6k1/H/FGNaDZMgSdraWIOcCkDs+7CrsldQgm8zSiGTvxEMzX3lkx9sKvCC8TQ9+pvjpEn2l8tz21RTN9ZT2taPa1o7kg1tb307/TddG7k9KatPdrAv0eUb1nJ5HUOzEns2+7sZWxQnXOCkzs4/W8D2g0EMHAVn1ZKY9S1/MryotEIdBJTyNT4bO7SbuPwti1bJuSmzwwIOYMjp3bRu4P93a1DyrOHtzPRfOugE3Ev4GTuP4XLFgHJpxQtN+E/pRTyMoQLpm8M6NKC2uQfBeMOxYaAv9U+LXEyzZIa1++jATbugXYSqP+npZsqxs6QBZcQBQ5cfo+QznQVQOp6RWipvkMWREKXOVSOsFsTnIVtj6+nMcyGU6UYQQFTjzUpEGoZa35/5tvfSNeGLIBC7Li0gJmtX6+xwqWdUsHxTX2AsTDDWSDyzUejXLi9SDGJpSF4l90jwTB/DGkC6hX1LSnZtXh9uCQrUyaL6fIsdcamdweYOdO9J0eucpSpWOAv5R1XBG2qd4GEufjxyV7iU6dttG4iDFmf5PaLIJi6GVW5f4hF8r7eVK66wCJVRUDMzHprXMMC5MWKDRXhsWhn1OF4IBix6FnatbuUaV18pbkPoWL4UcgxI2OnZn9vLg0o/iaTO5lswe300NSKvRA3HVjzHy/dIo3zzJSdF/wvsAuk2iRoBcIMYLAR+EqPH7kyDzqm6H/md6TVj0wyh1unWFzfgflNaTdPJA6TiQCO9xlh5iWzP4y+HhNnjl1UplHNnR1pkoVuJTQjV5jaMF2j79F6pk6qXcwA8Ul42ulXTDBGYcfTgRW/LdOzaifN4ewlSaYHSbAH9A+fjC/OzCKmFpsBgI0YSW2a4mBcip9oml9r2Usq87kEak+iT5Wd+RQxfxLHPB9OiFNPE7xv3L7hNlGaw2i8aAABt7yxec+klWeRWcEYQHmDkZsznNaG9uly6AtbGbQXDBf075sUPpn2Lz/vByV0NcEc3fdC8uyaDbiczSGbFU61nCZM5ougn8A9INMMmlTA6KHLGKsbIr2j3irKKkylVvOhNwxZU6hnxBbdEXWSEXy5I9l4nwF/8AZB2641LurOgqHZMd+3ZeAK0Qa8FzuO0XLgdMFkhLFwzybGwbaNpRfXY2mrzedzJla0cZg1sJLnLe1MsGirK6tA/4p+Nc6aFGW/pn0njI2RsXoCu5TZCc+Nfie6t+P1iA7O768g+H4FRe2y48UFuphUfOREsuRpocqGWO9JIrH3AE4lHoK2422zWczXPLpimIxkYJCMrU3WNuVWBdxB6+frORRnhgmzlIKwbb75IAXnPnHD2zWR+kPtrCX8qtpy05qCOt7PB8MTLmTFs/w+Trp1M0OdMNeINUfYaYgXMd7LKIU+1e4jfCCTzCwAdcvWqelw/thLkVzcLqsuiKLFOQzVMma96Y/9lTtnjxSINghQ2Quj5DGHCtwtGgd/JccGuDkO1mC8U9Y/6ctRgbZeaDcqvmAMldRZefBcRPJRagtWuaB2bErRssmA4RIB+2TBXwDiMrfvHofheUFAs14+uvfdfY16M3aNwKqeh0JZ1BYZfnjNdVENdrifi6qVv9fXp2kgFtXTHiLVHwKFgXzqk8+DQ9MTSY1ZOwCk8xmCxonJYmwFit2cQZxHGsTjBa+U/fcNz+FdOzEv/vXA3jqM9W399QemKTVeoZsLkD53NrvbWxGZVrfXLiKFpbX+Zq9GsMDVMWXbLdJOolCN7rS+SBgdFAPkLyxKUO/XvH5ni13mPNBt6E7Ii32frbQA1/MISy0q85MCNEV25QwhkvHnDgvnTeSo9pXI6O94SQIU+rqNrqXIibmWXVWbAc4N4IiOk9zFQNmM13NjQNKmP55VijGMI+B+44NKSoinSuVIFa1GzMulDHsFWg5/OAEv4yHt5d2RrgGgfxxBBFuVLhwTltjGclv7kqgWHpmKdMEL6m5PXpbYd7Zmvslu67gflc9E/jCkTFNpYHkzvcsKfzPFyXZRXYGZgazuwOGecL1b32NJrIiApYkndaqdC3BX9X2pRbCtmeRE442oOlXFfXumsT86QLLIfAb2pfSNYfs/V1d2sqgENJqWoZCkfQ0kouIMaEDfUrWpnpxECT6t1sqGUcrGamhHLL4mM8poMt39zB0Q5u7ot+7FG4LxF3cwtewRDnUb+fsJJhZVBhwJzfLH43ghGm/6NRdCmMy9TNN2VC4G9UTfF3dMeNx9nLupFI54Xt5L213Xi9cVQiiC3cQVFZnQF3bykE/DxDP5JwrjbuVr+ugcVXes+H1LJtCNHBuOQZQCaYPTwQLohtnuvIzJioVK/QCcWLsWstg9/U10Y/si48DjvhzooDFpd9TATujaVEY25C9RZ+99Ep2NA9WbvMxAKXa5Kw6u+LULBUvPeE6dI3TqJZN4YDmaud92qsTbaFGl9YNpnigXWv4I+7GF5PWQqwHrRW4TahWSPZguC6DQkhHD+E4Nmo/R7qutASwPlVm0wBqWEdz8u96eVQbdN+ydCzAzMFy5CQVroiNfVlqdPfHROpQUPTn3/Cw8u4eupo5IMz/LKDEzlFMR0C9zAaeUrlDMqdIyyDYnbg/Evzmt2HsP6FaoKt+yBt6acRn1KrP6Hmg37IEz2qtPerLs/YlbOIHjU/ZJclp/C9O0ogLKlle1q0SGpJCVCKd1+y2x1TxLjsdeb9chMkT4Y6R7aDds9Qg4HORa/oiOF8SB6+Y+mbmgKmjETPgWNcNKSYQPY9V1O5ESHUwDmGNGL3PS8obQN6a+dW5o0mq4gt7ThMrL8PnhfwtUZDyeZrIr7Kr3c+P8/9V05VxsXzIHWMj1u3RO941ZiWsFysMN/Fo6lO9MEM4G83OnfJeA3OvmUBGfgCvXrpmhlIp5UUveqJAfpjMnVrBnN0HmFLjDjyRtAW6KpydCxn8ld7djPVQJtG37ER3WzFz8fZDyUWvKkVDpeWpkS9rBFDladD4nrRCWhrFeSMK83fm8HDppSrGMzR+HF0ZtKFxMMpkyGh0hoQ5DWevGAEOJ6Mt1wwn0NIQi7zmhlZAn9oxeoJAI35CognnMm/8uKYouvAJjQ6p1I0D1q5sKnA6r15SaaVmT7+QcJvCRp1acv4DWukAMX5lKuwGIGcqWvpjgcMCLWb3ds86LIQhI6/Afyf32BXu9UgtAUExCpVcBycv5PN6UtZVsu839jTS0b3+EubFW4zrnfZv1Qg2uAFHkFyNhi27p8mbdffU8AClb4Vakxwu6+ZJn1r3SIiOFMfAwipWYISqr+if9sMs+WGZzbL51lgE0rXaN0xL/NkLgeVJ8Ri60ZyrJJdDM4GnhajMiv0qHqnxt33D171rbefvchhcrlzwcFoPWZbMumfykZ2sWVLUi4Lx1wVh+siftEwG19+jrCx7cxnf9ulZFVee1HFTd2N4eJScghWiGFA1pVul9afIuAVdsoMcAb6thwDapO0OZvqUKuzs17GtyXDPSPqg51YgGNEUAkLEO0q4/kAIHCJwOSXkPM0Ut/3L2MtKVFL2kE7MY/tlsFjABpYThGSsGy9SllvnkgWNceNcPWeJTPvUfzoY1RC0fsNuOEDaoBRUIecA1/y+JwxYrlMx9eW1gORt1XK8rgzXxK9DF6wt4SbdarjtZnS+9ieYpCnvLzrTwi431HCKKGa/sgH9TItWqQ4TqbBdyonSjWySkZbGivw/MbZfxJfdRRyLqq2PQlfYgxVq/9uieT1BGLnzVV9dgyPFJZA9UbAZ4b2wB/37u1LK4VQ3S1ig172CkrCyZ7RBf6+L48CCq7V9gjkar/6BRqzoE2nDV/QMl2n0xQ+hPVfW06ijdmddOFi25Mt2ZieVeMCaJ/u1NkY+E27XBzLcV2lnpF8EiK1eNz8F8J9g98rm0mXdDoVP5WYS0urs0PJPEOlSSjyYfaX3n/t4Ts7gdNqdZu0IKM6JUiS77aDf8JBp5a2c2rK+mze39NdR9NeTgHNH6/VnweXgtZvVGHB70zjj0K5E+3UC1uXoAJef6qfSUvuyiqe8SLxyE0xF9OtfG2MIdCBhwKyHIZHKC83qWF7kCXMl8cCg6bVsoPGudNZ5NKpXoHUiYgG76lNmd7i/w7L0ja7MDArU4DZw4MrebK63SuJ9DG5Jk0HT/NWLGq4oKhGujA/641eOVn9GKRReUYfrSWkJgGnPg/asUvaNO1M3UNHZL3utVlH5xfGer+QsuxG2MocB07e0g7ugi/4uUjsdKbT+bqbUxiQjkAASjPCyAEzG3eVT0fpz3CGlVZtv28nZnTkI/VEGMNZNRRm7RxkDiDuHxaC90o6AXUPm9dScr8LTgkNZb7R2BiaF2nVDnr0XIGHJ0uzl4NTGJjw8vQwSDIfbMXhrVZuKaCcjWMc4+vF2hllueLc6XOepX0jpEpUxe3cqFETgmBu7rsJ/Tvwa9Udc4lkDxdGi3eo7DstXjlADQTq2E9w1mhWXgB6Be+mbLNyirRD7vic0qyZ+EbbSV70PikKNPCAKR2xXPhuPYROFM2hoqgy76+p/QXfI2vuvuVCTyoFYcSHZPNKkLZ4irD9DiYWPx27sEU9swcfimEQWrzEB2+MKxVpss4ljs/UVtZQ9Bvi8+b0E9z6kA9r2OTDVTErKuP6pK6qB7HT34nh8pdaUncbVLLN2jTGFAwGt0CtN9kBnd6V3F6pHvvVuo4It22iv9F+fzd85sDMQPfhGV599xpOBTmsclbVZpWRVEW5t7FGAg+m4sbk1Q8cxNFQIDM7pwBxdqnUWv1JvaoMKXO/nYucV1kqfC3+zTexllpFnth44xdSQF8KSZsHe9rP+7EgTrZtAD+MPaTR96EiPa5yo+/8tZHoQP15LLHNcfIwEzUc5Dtb4rorqWmY8NCjC6TVDKSt6dLzq18+zz8lKIufMcY3USmn6BPxFpyuvhGq6xVZKAvobfL0z5/3+s6qDhcJe3FwkXRzynUU5fxHr3Gt6r/7wpPWeb2sj6Gy/YmcEU4bmTvXgINmhkZDyKHiezxfUrQX3O+zP5FP98nCq5mz2jBqYrw80K/3xH7PVws0fSRTpCo70QKSdj29LULM5oTe1dVY2xXJ3iuFLKVIsPKhTz/DI7BX/u9QEhzwq9Vp+mlEoQEP3o7W3bU5j0raVis7kkbGxWsmjQPaxeWuXtFUtL+qCvBVGuyItRqAvMQB5FM2xlmDs28innw8Kqilf8JGuBmPSuVHMNvcURPzUk8km72LmYvsNep026ADpHuBXs+ScFDgLpYHOOgARXNSFuMpdnGoj9y9z/fo09X7bhcbWRPKFu2aVcLuEyHBPTCcyARzxDpA5/cIE23msIqP16DwIHIhyIDgjiU14zd0WwkopKLqdhRb+p9jVD7CYxGsIFjLxY7iqQmpLyD7MzJES/La7sc0Ck7joI5omUFyvC4dyBXfZpdvkzaai7UxPW6g3llVQAIj+XqaL+dGLgl+sAumWxy/evduwB09UJQifd/PngkP6jTP0j/jkH3GhJmnUvH70I0Rt/U3ygsI81KOuKgSRfWRlME0Z/5ljgdCVi1YaB433h9S96qzl4seubpCv/MNcs7WgM1/6Sy3bQr8TzyTe3Jbt8kz0nK9B+BsB4ps2Ks9OLN8yRx2FCcrIQ/FxQKsIqM0JDR+VvtrVP9M9lnAK9ctd9P/v/0KDgONm9inKhcKY4ulurhkpda0Yl7SSD0kntWEVISua+laNBFCeleSo9EWVY2x1xxg0D1FJ9e1f+p9qCwO9aKm9urbIwjYfJH97IWCSDMfj5PK6KL9hmOR41Va5As/nOm/JNeq5KPvMLQfLilfUvtcn5t2z7CU/ku4u8E7jD18VhRxgQkMIEmO2xOovcGpMxV4pz88u6g4JBqm8qkKdUsc15qggzZOSwSnqmepfKqAnaytK8fHLC4weeLel+mTtSOYMLGQGOdV9cs5N40qGSUyLtjfPsyO8OedZcl3BmCoeosfDA0im1s2/Crj/IrrVbBZHNIGRI9e5kehlc1RfIiEF1tiV4zKTXuoVi5aEXU38C+/iBptx/SAiDiwX9/D7vI8Ac7hM08mqpZquXIq3RGXXeDmJTKPh+xTKDj1rXf9RNCWIDdLldcAaLugoo5mybuOwJUTGoj1LbFTfri9oirphEgJ7Qlu9cUkfMvRAXNryOXbkED9RFcvsiPTsnLajczpBL17e6qXiECSXOK/lsOiKvBDmaAwzMrwCFc/SOvFGtjLiNWjoOL0hj4H7t4voUAkM0omYhEi8oBVZXnHRQ6tZoZvDTuwx8WejWvdP8p8517kVEeZz8cfsA6eo0hYRykwsNov7w/peeiifbb9oU3+dOA2scvE/wxxoLuZ6zCaxJL9bAxVgICQB9ELXDheNuYmKGEygiBXkWSZOOLI//SgGm5Un/DB+6bgfKYt52yDabfMRK+qxdnKB5UZL0xyeQ7yn1wU6PcwkhOQM4o8KIc6FiN/CgFWEAwrdhZ72NFAPbK/c+UyC6RHj82BP5FBjTdoyR20ujPfBfTNju2SaYYWHojRRfXe2Zzuqn/uD+qJALF4245Wh0epVozNTI84d6aZpL9iKZcRpdMNhD2e4zH/Pxa8rDO8wdzCSnYsSI56UuFle3WDf1HFpqLp7VdcvPj7tYp7Wj3hzqSxm8Md4FKxOLDPxBHlatXMxQL6y/dOxfczFIrwvfQqbtFQSOi2Ra1+O9XgvjGSJLL/ZvnW3qG8kk2dprn2s4STGqbH5IhKHSBPWzitkF8tsebraKFQxiUWJCj2VodK23uONtbL4yHhB3dbKIFXofOfluRUbCW4FzwOCd92iqtKInDHsLz5BZiSNLUJD+iwxzAAa/QMO+eKSyeC7holK2dekMq9GZ99OLaog9/W/gsvUW/vrHL/kDKWKFMwhCVfe3MUNmSUvPsiKi80UJkpYcMrxcb7hr3aKj7M3BxuEkV6hWma+iedhAl28Rh15KdUYtNghnL/uN4cgXg6fSIOJllcG822FqwAMT7mTiVxisGg2BLejXYZMO3LtczCeV1fwSphcfshZrhm9XKE2+R2/NU2ocPI3CB5ha+CFvnjyFUchclS26OlF/0rvD/GQKFN0xublEniL3EzCvxUwBiHIbc+G+N2T2MDV8/H3rBkGzEZi0TXKvqt9jHuzlZYGrkX4k3spLPmWc+bbksjVt4BX7ulKQtOlooCIBVQCg5n3cf1uzl27WLZt9CHkLghIJoeghILNL56+ly6jISfiqFbLt3R6mi2JMVbl34Ec+BK7lTIEQhMDPQD7cM3Eh4F8RMaJtAkxjVVEO1cCa2JJdZq+9HvFkfBMiRvlaxy7qroNdgif77EG+vz6TentsHX1VUqPYrE+IES1J1td/iSVYpk8AoGFi3J7q6dDqudEGVpRk4k4IHicL+2kSa5C0sfpXVHvtYSrlA488ZACcGolFjZIwOLtWt9f2tDT2UcGTS6tQG/eXhpnoVNN4TRtwwJ5Gs5XCROr6TbE2PvzT5sZZCcFUjSNfrrI05N0WV5E0v3tCOMuYfzie52WfqoWQDO9yKdaedtKHvdTLA37T6k5PN45fiK+zm4rDo7KtMavCs6ejnG1uHFGahIPLxXsszHAY6nCLTxfa4D1xQajhTcpyeLoqexEboX6ZjbZMrJKopmkmknh20Vqher1sE7sadJ4xA5Nb3uYIgMvhUavWgZuPxHuEwhc8Vbc1OOnUq0FUGwXXT046BlnSvFGujAvjL+fSqNky/D68NximVzAXJnDIZSmHgppOW2kTAAR008k/VVocIEnRUQq9NYesqbLwiMCaq0OwJj1TBuW2UKCrTq4cod1aML1HNYU4qEI4tQBXT0kfUrXNyj08KVbNWsc11aqtvuRkKd738TR33QZNE6w97NRJGGjlQQs7yM2a9HlpROBWDur2TDNpdp5hmjhU1w6fV4A19RiAKwJoGM/jK6T7jjPVshQzM3q2iuUzuQlIB1FCEvVeSC/FrBITrU1cwp+buxLta/AzWGIDehPtj2W5/L4upMuX7U7h82whzfGBNSsJzdpC8HJADp/8sMb4aA4tnQogHSKdscIAYYXDU7sZU2ZS1uhmtPvKzMbsngndnf0v3fWkEAs2kHX3Gv1IS4DZSzaPHJVMR6/QD1Ok/cCZUTdn0dXoHEozgvAwCEezIP7VtmIp28aR7p9QxToWgOyIAAAA';

// ── Classe d'erreur métier ─────────────────────────────────────
class ApiError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.status = status;
  }
}

function securityHeaders(extra = {}) {
  return {
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'Content-Security-Policy':
      "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
      "font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self'; " +
      "frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    ...extra,
  };
}

function secureEquals(left, right) {
  const a = String(left || '');
  const b = String(right || '');
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let index = 0; index < a.length; index += 1) {
    diff |= a.charCodeAt(index) ^ b.charCodeAt(index);
  }
  return diff === 0;
}

function getAllowedOrigins(env, requestUrl) {
  const configured = String(env.CORS_ALLOWED_ORIGINS || '')
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);
  return new Set([requestUrl.origin, ...configured]);
}

function buildCorsHeaders(request, env, requestUrl) {
  const origin = String(request.headers.get('Origin') || '').trim();
  const allowedOrigins = getAllowedOrigins(env, requestUrl);
  const allowOrigin = origin && allowedOrigins.has(origin) ? origin : requestUrl.origin;
  return {
    'Access-Control-Allow-Origin': allowOrigin,
    'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Vary': 'Origin',
  };
}

const ADMIN_SESSION_COOKIE = 'affbc_calendar_session';
const ADMIN_SESSION_TTL_MS = 12 * 60 * 60 * 1000;
const CLUB_CONTACT_EMAIL = 'fullfightingbons@gmail.com';
const MAIL_SENDER_EMAIL = 'contact@americanfullfightingbons.fr';

function parseCookies(request) {
  const raw = request.headers.get('Cookie') || '';
  return Object.fromEntries(
    raw.split(';')
      .map((chunk) => chunk.trim())
      .filter(Boolean)
      .map((chunk) => {
        const index = chunk.indexOf('=');
        if (index < 0) return [chunk, ''];
        return [chunk.slice(0, index), decodeURIComponent(chunk.slice(index + 1))];
      })
  );
}

function toBase64Url(value) {
  return btoa(value).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function fromBase64Url(value) {
  const padded = value.replace(/-/g, '+').replace(/_/g, '/') + '==='.slice((value.length + 3) % 4);
  return atob(padded);
}

function bytesToBase64Url(value) {
  const bytes = value instanceof Uint8Array ? value : new Uint8Array(value);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

async function hmacSha256Base64Url(secret, value) {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value));
  return bytesToBase64Url(signature);
}

function getSessionSecret(env) {
  const secret = String(env.SESSION_SECRET || '');
  if (secret.length < 32) {
    throw new Error('SESSION_SECRET manquant ou trop court (32 caractères minimum). Configurez-le dans les secrets Cloudflare.');
  }
  return secret;
}

async function createSessionToken(payload, env) {
  const encodedPayload = toBase64Url(JSON.stringify(payload));
  const signature = await hmacSha256Base64Url(getSessionSecret(env), encodedPayload);
  return `${encodedPayload}.${signature}`;
}

async function parseSessionToken(token, env) {
  const [payload, signature] = String(token || '').split('.');
  if (!payload || !signature) return null;
  const expected = await hmacSha256Base64Url(getSessionSecret(env), payload);
  if (!secureEquals(expected, signature)) return null;
  try {
    return JSON.parse(fromBase64Url(payload));
  } catch {
    return null;
  }
}

function buildSessionCookie(token) {
  return `${ADMIN_SESSION_COOKIE}=${encodeURIComponent(token)}; HttpOnly; Path=/; Max-Age=${Math.floor(ADMIN_SESSION_TTL_MS / 1000)}; SameSite=Lax; Secure`;
}

function clearSessionCookie() {
  return `${ADMIN_SESSION_COOKIE}=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax; Secure`;
}

async function loadActiveRegistrationCount(db, eventId) {
  const result = await db.prepare(
    `SELECT COUNT(*) AS total
     FROM registrations
     WHERE event_id = ?
       AND paiement_status IN ('en_attente', 'paye', 'gratuit')`
  ).bind(eventId).first();
  return Number(result?.total || 0);
}

function withComputedEventState(event, activeRegistrations) {
  const spotsTotal = Number(event?.spots_total || 0);
  const spotsLeft = Math.max(0, spotsTotal - activeRegistrations);
  const forcedClosed = event?.status === 'ferme';
  const status = forcedClosed
    ? 'ferme'
    : spotsLeft <= 0
      ? 'complet'
      : 'disponible';
  return {
    ...event,
    spots_total: spotsTotal,
    spots_left: spotsLeft,
    status,
    registrations_count: activeRegistrations,
  };
}

async function hydrateEvent(db, event) {
  const activeRegistrations = await loadActiveRegistrationCount(db, event.id);
  return withComputedEventState(event, activeRegistrations);
}

/**
 * Hydrate une liste d'événements en une seule requête agrégée (évite le N+1).
 * Pour chaque eventId, compte les inscriptions actives en une passe SQL.
 */
async function hydrateEvents(db, events) {
  if (!events || events.length === 0) return [];
  if (events.length === 1) return [await hydrateEvent(db, events[0])];

  const ids = events.map(e => e.id);
  const placeholders = ids.map(() => '?').join(', ');
  const rows = await db.prepare(
    `SELECT event_id, COUNT(*) AS total
     FROM registrations
     WHERE event_id IN (${placeholders})
       AND paiement_status IN ('en_attente', 'paye', 'gratuit')
     GROUP BY event_id`
  ).bind(...ids).all();

  // Index des comptes par event_id pour O(1) lookup
  const countByEventId = new Map();
  for (const row of (rows?.results || [])) {
    countByEventId.set(row.event_id, Number(row.total));
  }

  return events.map(event => withComputedEventState(event, countByEventId.get(event.id) ?? 0));
}

async function syncEventAvailability(db, eventId) {
  const event = await db.prepare(`SELECT * FROM events WHERE id = ?`).bind(eventId).first();
  if (!event) return null;
  const hydrated = await hydrateEvent(db, event);
  await db.prepare(
    `UPDATE events
     SET spots_left = ?, status = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
     WHERE id = ?`
  ).bind(hydrated.spots_left, hydrated.status, eventId).run();
  return hydrated;
}

// ── Validation événement ───────────────────────────────────────
function validateEvent(body) {
  const required = ['title', 'sub', 'type', 'date_start', 'lieu'];
  for (const f of required) {
    if (!body[f]) throw new ApiError(`Champ requis manquant : ${f}`);
  }
  // Validation format date ISO YYYY-MM-DD
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(body.date_start))) {
    throw new ApiError('date_start doit être au format YYYY-MM-DD');
  }
  if (body.date_end !== undefined && body.date_end !== null && body.date_end !== '') {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(String(body.date_end))) {
      throw new ApiError('date_end doit être au format YYYY-MM-DD');
    }
    if (body.date_end < body.date_start) {
      throw new ApiError('date_end ne peut pas être antérieure à date_start');
    }
  }
  const validTypes = ['stage', 'competition', 'seminaire', 'grade'];
  if (!validTypes.includes(body.type)) {
    throw new ApiError(`Type invalide. Valeurs : ${validTypes.join(', ')}`);
  }
  const validStatuses = ['disponible', 'complet', 'ferme'];
  if (body.status && !validStatuses.includes(body.status)) {
    throw new ApiError(`Statut invalide. Valeurs : ${validStatuses.join(', ')}`);
  }
  // Validation prix : nombre non négatif
  if (body.price !== undefined && body.price !== null) {
    const price = Number(body.price);
    if (Number.isNaN(price) || price < 0) {
      throw new ApiError('price doit être un nombre positif ou nul');
    }
  }
  // Validation places : entier non négatif
  if (body.spots_total !== undefined && body.spots_total !== null) {
    const spots = Number(body.spots_total);
    if (!Number.isInteger(spots) || spots < 0) {
      throw new ApiError('spots_total doit être un entier positif ou nul');
    }
  }
}

// ── Validation inscription ─────────────────────────────────────
function validateRegistration(body) {
  const required = ['event_id', 'nom', 'prenom', 'date_naissance', 'telephone', 'email'];
  for (const f of required) {
    if (!body[f]) throw new ApiError(`Champ requis manquant : ${f}`);
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email)) {
    throw new ApiError('Email invalide');
  }
  if (body.is_mineur && (!body.parent_nom || !body.parent_prenom || !body.parent_tel)) {
    throw new ApiError('Informations du représentant légal requises pour un mineur');
  }
}

function isUniqueConstraintError(error, indexName) {
  const message = String(error?.message || error || '');
  return message.includes('UNIQUE constraint failed')
    || (indexName && message.includes(indexName));
}

// ── HelloAsso OAuth2 ───────────────────────────────────────────
async function getHelloAssoToken(env) {
  const resp = await fetch('https://api.helloasso.com/oauth2/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type:    'client_credentials',
      client_id:     env.HELLOASSO_CLIENT_ID,
      client_secret: env.HELLOASSO_CLIENT_SECRET,
    })
  });
  if (!resp.ok) throw new ApiError('Erreur authentification HelloAsso', 502);
  const data = await resp.json();
  return data.access_token;
}

// ── HelloAsso — créer une session Checkout ─────────────────────
async function createHelloAssoCheckout(env, { eventTitle, amount, email, prenom, nom, returnUrl, errorUrl }) {
  const token = await getHelloAssoToken(env);
  const resp = await fetch(
    `https://api.helloasso.com/v5/organizations/${env.HELLOASSO_ORG_SLUG}/checkout-intents`,
    {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        totalAmount:      amount * 100,
        initialAmount:    amount * 100,
        itemName:         eventTitle,
        backUrl:          errorUrl,
        errorUrl:         errorUrl,
        returnUrl:        returnUrl,
        containsDonation: false,
        payer: { email, firstName: prenom, lastName: nom }
      })
    }
  );
 if (!resp.ok) {
    let e = {};
    try { e = await resp.json(); } catch(_) {}
    const detail = e?.message || e?.error || e?.errors?.[0]?.message || JSON.stringify(e);
    console.error('HelloAsso checkout error:', JSON.stringify(e));
    throw new ApiError('Erreur HelloAsso : ' + detail, 502);
  }
  const data = await resp.json();
  return data.redirectUrl;
}

// ── Brevo — envoi d'email ──────────────────────────────────────
async function sendBrevoEmail(env, { to, toName, subject, html }) {
  if (!env.BREVO_API_KEY) {
    console.error('BREVO: clé API manquante — emails non envoyés');
    return { ok: false, error: 'missing_api_key' };
  }
  console.log('BREVO: tentative envoi à', to, '| sujet:', subject);
  try {
    const resp = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'accept':       'application/json',
        'api-key':      env.BREVO_API_KEY,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        sender:  { name: 'AMERICAN FULL FIGHTING BONS EN CHABLAIS', email: MAIL_SENDER_EMAIL },
        to:      [{ email: to, name: toName }],
        subject,
        htmlContent: html,
      }),
    });
    const body = await resp.json().catch(() => ({}));
    if (!resp.ok) {
      console.error('BREVO: erreur HTTP', resp.status, JSON.stringify(body));
      return { ok: false, status: resp.status, body };
    } else {
      console.log('BREVO: succès', resp.status, JSON.stringify(body));
      return { ok: true, status: resp.status, body };
    }
  } catch(e) {
    console.error('BREVO: exception réseau', e.message);
    return { ok: false, error: e.message };
  }
}

/**
 * Échappement HTML pour les corps d'email (texte libre saisi par le public :
 * nom, prénom, message, catégorie...). Les clients mail filtrent en général
 * <script>, mais pas le reste du HTML — sans échappement, un participant
 * pourrait casser la mise en page (balises non fermées) ou injecter un lien
 * trompeur affiché comme venant du club (le mail est envoyé depuis le
 * domaine officiel, donc plus crédible qu'un email de phishing classique).
 */
function escapeHtmlEmail(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

async function sendConfirmationEmails(env, { reg, ev }) {
  const CLUB_EMAIL = CLUB_CONTACT_EMAIL;
  const CLUB_NAME  = 'AMERICAN FULL FIGHTING BONS EN CHABLAIS';
  const prix       = ev.price === 0 ? 'Gratuit' : `${ev.price} €`;
  const dateStr    = new Date(ev.date_start).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' });
  const isConfirmed = reg.paiement_status === 'gratuit' || reg.paiement_status === 'paye';
  const participantTitle = isConfirmed ? '✅ Inscription confirmée' : '⏳ Inscription enregistrée';
  const participantIntro = isConfirmed
    ? 'Votre inscription à l\'événement suivant a bien été confirmée :'
    : 'Votre demande d\'inscription a bien été enregistrée. Le paiement ou le dossier doit encore être vérifié pour finaliser votre participation :';
  const participantStatus = reg.paiement_status === 'gratuit'
    ? '✓ Gratuit'
    : reg.paiement_status === 'paye'
      ? '✓ Payé'
      : '⏳ En attente de validation';
  const participantSubject = isConfirmed
    ? `✅ Inscription confirmée — ${ev.title}`
    : `⏳ Inscription enregistrée — ${ev.title}`;
  // Note : pas d'échappement HTML nécessaire dans le sujet (texte brut, pas de rendu HTML).

  const participantHtml = `<!DOCTYPE html><html lang="fr"><body style="font-family:sans-serif;color:#222;max-width:600px;margin:0 auto;padding:20px">
  <div style="background:#050505;padding:20px 24px;border-radius:8px 8px 0 0;text-align:center">
    <span style="font-family:sans-serif;font-size:22px;font-weight:900;letter-spacing:2px;color:#fff">AMERICAN FULL FIGHTING</span><br>
    <span style="color:#aaa;font-size:13px">Bons-en-Chablais · FFK</span>
  </div>
  <div style="border:1px solid #eee;border-top:none;padding:28px 24px;border-radius:0 0 8px 8px">
    <h2 style="color:#E10600;margin-top:0">${participantTitle}</h2>
    <p>Bonjour <strong>${escapeHtmlEmail(reg.prenom)} ${escapeHtmlEmail(reg.nom)}</strong>,</p>
    <p>${participantIntro}</p>
    <table style="width:100%;border-collapse:collapse;margin:16px 0">
      <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600;width:40%">Événement</td><td style="padding:8px 12px">${escapeHtmlEmail(ev.title)}</td></tr>
      <tr><td style="padding:8px 12px;font-weight:600">Date</td><td style="padding:8px 12px">${dateStr}</td></tr>
      <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600">Lieu</td><td style="padding:8px 12px">${escapeHtmlEmail(ev.lieu)}</td></tr>
      <tr><td style="padding:8px 12px;font-weight:600">Montant</td><td style="padding:8px 12px;font-weight:700;color:#E10600">${prix}</td></tr>
      <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600">Statut dossier</td><td style="padding:8px 12px">${participantStatus}</td></tr>
    </table>
    <p style="color:#666;font-size:13px">Pour toute question, contactez-nous à <a href="mailto:${CLUB_EMAIL}">${CLUB_EMAIL}</a>.</p>
    <p style="color:#666;font-size:13px">À bientôt sur le tatami 🥊</p>
    <hr style="border:none;border-top:1px solid #eee;margin:20px 0">
    <p style="color:#aaa;font-size:11px;text-align:center">${CLUB_NAME} · Saison 2025–2026</p>
  </div>
</body></html>`;

  const clubHtml = `<!DOCTYPE html><html lang="fr"><body style="font-family:sans-serif;color:#222;max-width:600px;margin:0 auto;padding:20px">
  <h2 style="color:#E10600">🥊 Nouvelle inscription — ${escapeHtmlEmail(ev.title)}</h2>
  <table style="width:100%;border-collapse:collapse">
    <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600;width:40%">Participant</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.prenom)} ${escapeHtmlEmail(reg.nom)}</td></tr>
    <tr><td style="padding:8px 12px;font-weight:600">Email</td><td style="padding:8px 12px"><a href="mailto:${encodeURIComponent(reg.email)}">${escapeHtmlEmail(reg.email)}</a></td></tr>
    <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600">Téléphone</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.telephone)}</td></tr>
    <tr><td style="padding:8px 12px;font-weight:600">Date de naissance</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.date_naissance)}</td></tr>
    <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600">Catégorie</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.categorie) || '—'}</td></tr>
    <tr><td style="padding:8px 12px;font-weight:600">Montant</td><td style="padding:8px 12px;font-weight:700">${prix}</td></tr>
    <tr style="background:#f9f9f9"><td style="padding:8px 12px;font-weight:600">Statut paiement</td><td style="padding:8px 12px">${reg.paiement_status}</td></tr>
    ${reg.message ? `<tr><td style="padding:8px 12px;font-weight:600">Message</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.message)}</td></tr>` : ''}
    ${reg.is_mineur ? `<tr style="background:#fff3cd"><td style="padding:8px 12px;font-weight:600">⚠ Mineur</td><td style="padding:8px 12px">${escapeHtmlEmail(reg.parent_prenom)} ${escapeHtmlEmail(reg.parent_nom)} — ${escapeHtmlEmail(reg.parent_tel)}</td></tr>` : ''}
  </table>
</body></html>`;

  const [participantEmail, clubEmail] = await Promise.all([
    sendBrevoEmail(env, {
      to: reg.email, toName: `${reg.prenom} ${reg.nom}`,
      subject: participantSubject,
      html: participantHtml,
    }),
    sendBrevoEmail(env, {
      to: CLUB_EMAIL, toName: CLUB_NAME,
      subject: `🥊 Nouvelle inscription — ${ev.title} — ${reg.nom} ${reg.prenom}`,
      html: clubHtml,
    }),
  ]);

  return { participant: participantEmail, club: clubEmail };
}

// ── Rate limiting simple par IP (en mémoire, par isolat Worker) ──
const rateLimitMap = new Map();
function isRateLimited(ip, limit = 10, windowMs = 60_000) {
  const now = Date.now();
  const entry = rateLimitMap.get(ip) || { count: 0, resetAt: now + windowMs };
  if (now > entry.resetAt) {
    entry.count = 0;
    entry.resetAt = now + windowMs;
  }
  entry.count++;
  rateLimitMap.set(ip, entry);
  // Nettoyage périodique pour éviter les fuites mémoire
  if (rateLimitMap.size > 5000) {
    for (const [k, v] of rateLimitMap) {
      if (now > v.resetAt) rateLimitMap.delete(k);
    }
  }
  return entry.count > limit;
}

// ── Exports pour les tests unitaires (fonctions pures uniquement) ──
export {
  ApiError,
  secureEquals,
  getAllowedOrigins,
  parseCookies,
  toBase64Url,
  fromBase64Url,
  withComputedEventState,
  validateEvent,
  validateRegistration,
  isUniqueConstraintError,
  isRateLimited,
};


/**
 * Archive l'instantané des inscriptions d'un événement (snapshot JSON dans
 * event_archives, téléchargeable en CSV depuis l'onglet Archives de l'admin),
 * puis supprime l'événement. DELETE FROM events déclenche ON DELETE CASCADE
 * sur registrations — sans cet archivage préalable, les données de présence/
 * paiement disparaîtraient définitivement avec l'événement.
 * Utilisée à la fois par la suppression manuelle (admin) et par le cron
 * purgeExpiredEvents() ci-dessous.
 * @returns {Promise<{archived_registrations: number}|null>} null si l'événement n'existe pas.
 */
async function archiveAndDeleteEvent(db, eventId) {
  const eventRow = await db.prepare(`SELECT * FROM events WHERE id = ?`).bind(eventId).first();
  if (!eventRow) return null;

  const { results: regsToArchive } = await db.prepare(
    `SELECT * FROM registrations WHERE event_id = ? ORDER BY created_at ASC`
  ).bind(eventId).all();

  await db.prepare(`
    INSERT INTO event_archives (event_id, title, type, date_start, date_end, lieu, registrations_count, registrations_json)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `).bind(
    eventRow.id, eventRow.title, eventRow.type, eventRow.date_start, eventRow.date_end, eventRow.lieu,
    regsToArchive.length, JSON.stringify(regsToArchive),
  ).run();

  await db.prepare(`DELETE FROM events WHERE id = ?`).bind(eventId).run();
  return { archived_registrations: regsToArchive.length };
}

// ── Suppression + archivage automatiques des événements expirés (cron J+5) ──
// Activé via [triggers] crons dans wrangler.toml (cron quotidien). Chaque
// événement dont la date de fin (ou de début si pas de date_end) est passée
// depuis plus de 5 jours est automatiquement archivé (cf. archiveAndDeleteEvent
// ci-dessus — instantané JSON des inscriptions conservé dans event_archives,
// téléchargeable en CSV depuis l'onglet Archives de l'admin) puis retiré du
// calendrier. Aucune donnée d'inscription/paiement n'est perdue : seul
// l'événement disparaît de la liste active.
async function purgeExpiredEvents(env) {
  const { results: expired } = await env.DB.prepare(`
    SELECT id FROM events
    WHERE (
      CASE
        WHEN date_end IS NOT NULL AND date_end != ''
          THEN date_end
        ELSE date_start
      END
    ) < date('now', '-5 days')
  `).all();

  let archivedEvents = 0;
  let archivedRegistrations = 0;
  for (const { id } of expired) {
    const result = await archiveAndDeleteEvent(env.DB, id);
    if (result) {
      archivedEvents += 1;
      archivedRegistrations += result.archived_registrations;
    }
  }
  console.log(`[cron] purgeExpiredEvents: ${archivedEvents} événement(s) archivé(s) puis supprimé(s), ${archivedRegistrations} inscription(s) archivée(s)`);
}

export default {
  // ── Cron trigger quotidien (cf. [triggers] crons dans wrangler.toml) ──
  async scheduled(_event, env, _ctx) {
    await purgeExpiredEvents(env);
  },

  async fetch(request, env) {
    const url    = new URL(request.url);
    const path   = url.pathname;
    const method = request.method.toUpperCase();

    if ((method === 'GET' || method === 'HEAD') && path === '/api/health') {
      return new Response(JSON.stringify({ ok: true, data: { service: 'calendrier-americanfullfightingbons', date: new Date().toISOString() } }), {
        headers: securityHeaders({ 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }),
      });
    }

    if ((method === 'GET' || method === 'HEAD') && path === '/api/version') {
      return new Response(JSON.stringify({ ok: true, data: { service: 'calendrier-americanfullfightingbons', version: '1.0.0' } }), {
        headers: securityHeaders({ 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }),
      });
    }

    if ((method === 'GET' || method === 'HEAD') && path === '/robots.txt') {
      return new Response('User-agent: *\nAllow: /\n\nSitemap: https://calendrier.americanfullfightingbons.fr/sitemap.xml\n', {
        headers: securityHeaders({ 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }),
      });
    }

    if ((method === 'GET' || method === 'HEAD') && path === '/sitemap.xml') {
      return new Response('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>https://calendrier.americanfullfightingbons.fr/</loc>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>\n</urlset>\n', {
        headers: securityHeaders({ 'Content-Type': 'application/xml; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }),
      });
    }

    // ── Logo servi directement par le Worker ──────────────────
    // Remplace l'ancien hot-link vers raw.githubusercontent.com/.../Logo.jpg (2,6 Mo,
    // dépendance non garantie en prod) par une version compressée (~24 Ko, WebP),
    // servie depuis le même domaine que le site avec un cache long (le contenu est figé).
    if ((method === 'GET' || method === 'HEAD') && path === '/logo.webp') {
      const bytes = Uint8Array.from(atob(LOGO_WEBP_BASE64), (c) => c.charCodeAt(0));
      return new Response(bytes, {
        headers: securityHeaders({
          'Content-Type': 'image/webp',
          'Cache-Control': 'public, max-age=31536000, immutable',
        }),
      });
    }

    // ── Servir index.html embarqué dans le Worker ─────────────
    if ((method === 'GET' || method === 'HEAD') && (path === '/' || path === '' || path === '/index.html')) {
      return new Response(INDEX_HTML, {
        status: 200,
        headers: securityHeaders({
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=300',
        }),
      });
    }

    // ── CORS ───────────────────────────────────────────────────
    const corsHeaders = buildCorsHeaders(request, env, url);
    if (method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: securityHeaders(corsHeaders) });
    }

    // ── Helpers internes ───────────────────────────────────────
    const json = (data, status = 200) =>
      new Response(JSON.stringify(data), {
        status,
        headers: securityHeaders({ ...corsHeaders, 'Content-Type': 'application/json' }),
      });

    const err = (msg, status = 400) => json({ error: msg }, status);

    const hasAdminSession = async () => {
      const token = parseCookies(request)[ADMIN_SESSION_COOKIE];
      if (!token) return false;
      const session = await parseSessionToken(token, env);
      return !!session && Number(session.expiresAt || 0) > Date.now() && session.role === 'admin';
    };

    const isAdmin = async () => {
      // Seule la session cookie HMAC est acceptée — le Bearer token statique a été supprimé
      // car il ne peut pas expirer et constitue un accès permanent si le token fuite.
      return hasAdminSession();
    };

    const requireAdmin = async () => {
      if (!(await isAdmin())) throw new ApiError('Non autorisé', 401);
    };

    const genId = (prefix = 'evt') => `${prefix}${Date.now().toString(36)}`;

    const segments = path.replace(/^\/api\//, '').split('/');
    const resource = segments[0];
    const resId    = segments[1];
    const subRes   = segments[2];

    try {
      if (resource === 'auth') {
        if (method === 'POST' && resId === 'login') {
          // Rate limiting : le mot de passe admin (ADMIN_TOKEN) est un secret unique
          // partagé par tout le bureau, sans verrouillage de compte possible — sans
          // limite ici, un brute-force est possible (même protection que sur les
          // inscriptions publiques, mais plus stricte vu la sensibilité de la cible).
          const clientIp = request.headers.get('CF-Connecting-IP') || request.headers.get('X-Forwarded-For') || 'unknown';
          if (isRateLimited(`login:${clientIp}`, 5, 5 * 60_000)) {
            return err('Trop de tentatives de connexion. Réessayez dans quelques minutes.', 429);
          }
          const body = await request.json();
          const password = String(body?.password || '').trim();
          if (!password || !secureEquals(password, String(env.ADMIN_TOKEN || '').trim())) {
            return err('Mot de passe incorrect', 401);
          }
          const token = await createSessionToken(
            { role: 'admin', expiresAt: Date.now() + ADMIN_SESSION_TTL_MS },
            env
          );
          return new Response(JSON.stringify({ ok: true }), {
            status: 200,
            headers: securityHeaders({
              ...corsHeaders,
              'Content-Type': 'application/json',
              'Set-Cookie': buildSessionCookie(token),
            }),
          });
        }

        if (method === 'GET' && resId === 'session') {
          return json({ ok: await isAdmin() });
        }

        if (method === 'POST' && resId === 'logout') {
          return new Response(JSON.stringify({ ok: true }), {
            status: 200,
            headers: securityHeaders({
              ...corsHeaders,
              'Content-Type': 'application/json',
              'Set-Cookie': clearSessionCookie(),
            }),
          });
        }
      }

      // ══════════════════════════════════════════════════════════
      //  EVENTS
      // ══════════════════════════════════════════════════════════
      if (resource === 'events') {

        if (method === 'GET' && !resId) {
          const { results } = await env.DB.prepare(`
            SELECT * FROM events
            ORDER BY
              CASE WHEN date_start >= date('now') THEN 0 ELSE 1 END ASC,
              date_start ASC
          `).all();
          return json(await hydrateEvents(env.DB, results));
        }

        if (method === 'GET' && resId) {
          const ev = await env.DB.prepare(
            `SELECT * FROM events WHERE id = ?`
          ).bind(resId).first();
          if (!ev) return err('Événement introuvable', 404);
          return json(await hydrateEvent(env.DB, ev));
        }

        if (method === 'POST') {
          await requireAdmin();
          const body = await request.json();
          const id   = body.id || genId('evt');
          validateEvent(body);
          await env.DB.prepare(`
            INSERT INTO events
              (id, title, sub, type, status, date_start, date_end, time_start, time_end,
               lieu, price, spots_total, spots_left, featured, is_grade, helloasso, helloasso_url)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
          `).bind(
            id, body.title, body.sub, body.type,
            body.status ?? 'disponible',
            body.date_start, body.date_end ?? null,
            body.time_start ?? null, body.time_end ?? null,
            body.lieu, body.price ?? 0,
            body.spots_total ?? 0, body.spots_left ?? body.spots_total ?? 0,
            body.featured  ? 1 : 0, body.is_grade  ? 1 : 0,
            body.helloasso ? 1 : 0, body.helloasso_url ?? null,
          ).run();
          const created = await syncEventAvailability(env.DB, id);
          return json(created, 201);
        }

        if (method === 'PUT' && resId) {
          await requireAdmin();
          const body = await request.json();
          validateEvent(body);
          await env.DB.prepare(`
            UPDATE events SET
              title = ?, sub = ?, type = ?, status = ?,
              date_start = ?, date_end = ?, time_start = ?, time_end = ?,
              lieu = ?, price = ?, spots_total = ?, spots_left = ?,
              featured = ?, is_grade = ?, helloasso = ?, helloasso_url = ?
            WHERE id = ?
          `).bind(
            body.title, body.sub, body.type, body.status ?? 'disponible',
            body.date_start, body.date_end ?? null,
            body.time_start ?? null, body.time_end ?? null,
            body.lieu, body.price ?? 0,
            body.spots_total ?? 0, body.spots_left ?? body.spots_total ?? 0,
            body.featured  ? 1 : 0, body.is_grade  ? 1 : 0,
            body.helloasso ? 1 : 0, body.helloasso_url ?? null,
            resId,
          ).run();
          const updated = await syncEventAvailability(env.DB, resId);
          if (!updated) return err('Événement introuvable', 404);
          return json(updated);
        }

        if (method === 'DELETE' && resId) {
          await requireAdmin();
          // Archivage automatique des inscriptions avant suppression (cf.
          // archiveAndDeleteEvent ci-dessus) — même logique que le cron
          // purgeExpiredEvents, déclenchée ici manuellement par l'admin.
          const result = await archiveAndDeleteEvent(env.DB, resId);
          if (!result) return err('Événement introuvable', 404);
          return json({ deleted: resId, archived_registrations: result.archived_registrations });
        }
      }

      // ══════════════════════════════════════════════════════════
      //  ARCHIVES — inscriptions des événements supprimés
      // ══════════════════════════════════════════════════════════
      if (resource === 'archives') {
        await requireAdmin();

        // GET /api/archives [admin] — liste des archives (sans le JSON complet)
        if (method === 'GET' && !resId) {
          const { results } = await env.DB.prepare(
            `SELECT id, event_id, title, type, date_start, date_end, lieu, registrations_count, archived_at
             FROM event_archives ORDER BY archived_at DESC`
          ).all();
          return json(results);
        }

        // GET /api/archives/:id/csv [admin] — export CSV de l'archive
        if (method === 'GET' && resId && subRes === 'csv') {
          const archive = await env.DB.prepare(`SELECT * FROM event_archives WHERE id = ?`).bind(resId).first();
          if (!archive) return err('Archive introuvable', 404);
          let regs = [];
          try { regs = JSON.parse(archive.registrations_json) || []; } catch { regs = []; }

          const headers = ['Nom', 'Prénom', 'Date de naissance', 'Téléphone', 'Email', 'Licence FFK', 'Mineur', 'Catégorie', 'Niveau', 'Régime', 'Parent', 'Téléphone parent', 'Message', 'Montant', 'Statut paiement'];
          const csvEscape = (value) => {
            const str = String(value ?? '');
            return /[";\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
          };
          const rows = regs.map(r => [
            r.nom, r.prenom, r.date_naissance, r.telephone, r.email, r.licence_ffk || '',
            r.is_mineur ? 'Oui' : 'Non', r.categorie || '', r.niveau || '', r.regime || '',
            r.is_mineur ? `${r.parent_prenom || ''} ${r.parent_nom || ''}`.trim() : '',
            r.is_mineur ? (r.parent_tel || '') : '',
            r.message || '', r.montant, r.paiement_status,
          ].map(csvEscape).join(';'));
          const csv = '\uFEFF' + [headers.join(';'), ...rows].join('\n');

          const safeFilename = String(archive.title || 'evenement')
            .normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 60) || 'evenement';
          return new Response(csv, {
            headers: securityHeaders({
              ...corsHeaders,
              'Content-Type': 'text/csv; charset=utf-8',
              'Content-Disposition': `attachment; filename="inscrits_${safeFilename}_${archive.date_start || ''}.csv"`,
            }),
          });
        }

        // DELETE /api/archives/:id [admin] — purge manuelle d'une archive
        // (une fois le CSV téléchargé et sauvegardé ailleurs si besoin)
        if (method === 'DELETE' && resId) {
          const info = await env.DB.prepare(`DELETE FROM event_archives WHERE id = ?`).bind(resId).run();
          if (info.changes === 0) return err('Archive introuvable', 404);
          return json({ deleted: resId });
        }
      }

      // ══════════════════════════════════════════════════════════
      //  REGISTRATIONS
      // ══════════════════════════════════════════════════════════
      if (resource === 'registrations') {

        // GET /api/registrations/public [public]
        if (method === 'GET' && resId === 'public') {
          const { results } = await env.DB.prepare(`
            SELECT e.id AS event_id,
                   e.title AS event_title,
                   e.date_start,
                   COUNT(r.id) AS registrations_count
            FROM events e
            LEFT JOIN registrations r
              ON r.event_id = e.id
             AND r.paiement_status IN ('en_attente', 'paye', 'gratuit')
            WHERE e.date_start >= date('now')
            GROUP BY e.id, e.title, e.date_start
            ORDER BY e.date_start ASC
            LIMIT 20
          `).all();
          return json(results);
        }

        // GET /api/registrations [admin]
        if (method === 'GET' && !resId) {
          await requireAdmin();
          const eventFilter  = url.searchParams.get('event_id');
          const statusFilter = url.searchParams.get('status');
          let query  = `SELECT r.*, e.title as event_title FROM registrations r JOIN events e ON e.id = r.event_id WHERE 1=1`;
          const params = [];
          if (eventFilter)  { query += ` AND r.event_id = ?`;        params.push(eventFilter); }
          if (statusFilter) { query += ` AND r.paiement_status = ?`; params.push(statusFilter); }
          query += ` ORDER BY e.date_start ASC, r.created_at ASC`;
          const stmt = env.DB.prepare(query);
          const { results } = await (params.length ? stmt.bind(...params) : stmt).all();
          return json(results);
        }

        // GET /api/registrations/:id [admin]
        if (method === 'GET' && resId && !subRes) {
          await requireAdmin();
          const reg = await env.DB.prepare(
            `SELECT r.*, e.title as event_title, e.price as event_price
             FROM registrations r JOIN events e ON e.id = r.event_id WHERE r.id = ?`
          ).bind(resId).first();
          if (!reg) return err('Inscription introuvable', 404);
          return json(reg);
        }

        // POST /api/registrations [public]
        if (method === 'POST' && !resId) {
          // Rate limiting : 10 inscriptions max par IP par minute
          const clientIp = request.headers.get('CF-Connecting-IP') || request.headers.get('X-Forwarded-For') || 'unknown';
          if (isRateLimited(clientIp, 10, 60_000)) {
            return err('Trop de requêtes. Veuillez patienter avant de réessayer.', 429);
          }

          const body = await request.json();
          validateRegistration(body);
          const normalizedEmail = String(body.email || '').toLowerCase().trim();
          const rawEvent = await env.DB.prepare(`SELECT * FROM events WHERE id = ?`).bind(body.event_id).first();
          const ev = rawEvent ? await hydrateEvent(env.DB, rawEvent) : null;
          if (!ev)                     return err('Événement introuvable', 404);
          if (ev.status === 'complet') return err('Événement complet', 409);
          if (ev.status === 'ferme')   return err('Les inscriptions sont fermées pour cet événement', 409);
          if (ev.spots_left <= 0)      return err('Plus de places disponibles', 409);

          // Vérifier qu'il n'existe pas déjà une inscription pour cet email + cet événement
          const existing = await env.DB.prepare(
            `SELECT id, paiement_status, montant FROM registrations WHERE event_id = ? AND email = ? AND paiement_status != 'annule'`
          ).bind(body.event_id, normalizedEmail).first();
          if (existing) {
            return json({
              error: 'Une inscription existe déjà pour cet email à cet événement.',
              code: 'duplicate_registration',
              existing_id: existing.id,
              paiement_status: existing.paiement_status,
              montant: existing.montant,
            }, 409);
          }

          const paiementStatus = ev.price === 0
            ? 'gratuit'
            : 'en_attente';

          let info;
          try {
            // INSERT...SELECT...WHERE : l'ensemble (comptage des places + insertion)
            // est exécuté comme une seule instruction SQL atomique côté D1, ce qui
            // élimine la race condition TOCTOU du contrôle ev.spots_left<=0 fait
            // juste au-dessus (deux requêtes simultanées sur la toute dernière place
            // pourraient sinon passer ce contrôle avant qu'aucune n'ait encore écrit
            // en base, et surbooker l'événement). Si la sous-requête WHERE est fausse
            // au moment de l'exécution réelle de l'INSERT, aucune ligne n'est insérée
            // (info.meta.changes === 0), ce qu'on détecte juste après.
            info = await env.DB.prepare(`
              INSERT INTO registrations (
                event_id, nom, prenom, date_naissance, telephone, email,
                licence_ffk, is_mineur, categorie, niveau, regime,
                ceinture_actuelle, ceinture_visee,
                parent_nom, parent_prenom, parent_tel,
                message, certif_medical, droit_image, reglement_ok,
                montant, paiement_status, helloasso_ref
              )
              SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
              WHERE (
                SELECT COUNT(*) FROM registrations r
                WHERE r.event_id = ? AND r.paiement_status IN ('en_attente', 'paye', 'gratuit')
              ) < (SELECT spots_total FROM events WHERE id = ?)
            `).bind(
              body.event_id, body.nom, body.prenom, body.date_naissance,
              body.telephone, normalizedEmail,
              body.licence_ffk       ?? null, body.is_mineur ? 1 : 0,
              body.categorie         ?? null, body.niveau    ?? null, body.regime ?? null,
              body.ceinture_actuelle ?? null, body.ceinture_visee ?? null,
              body.parent_nom        ?? null, body.parent_prenom  ?? null, body.parent_tel ?? null,
              body.message           ?? null,
              body.certif_medical ? 1 : 0, body.droit_image ? 1 : 0, body.reglement_ok ? 1 : 0,
              ev.price, paiementStatus, body.helloasso_ref ?? null,
              body.event_id, body.event_id,
            ).run();
          } catch (insertError) {
            if (!isUniqueConstraintError(insertError, 'idx_reg_unique_email_event')) {
              throw insertError;
            }
            const concurrent = await env.DB.prepare(
              `SELECT id, paiement_status, montant FROM registrations WHERE event_id = ? AND email = ? AND paiement_status != 'annule'`
            ).bind(body.event_id, normalizedEmail).first();
            return json({
              error: 'Une inscription existe déjà pour cet email à cet événement.',
              code: 'duplicate_registration',
              existing_id: concurrent?.id ?? null,
              paiement_status: concurrent?.paiement_status ?? paiementStatus,
              montant: concurrent?.montant ?? ev.price,
            }, 409);
          }

          if (info.meta.changes === 0) {
            // La sous-requête WHERE a empêché l'insertion : plus de place au moment
            // exact de l'écriture, alors que le contrôle initial l'avait laissé passer.
            await syncEventAvailability(env.DB, body.event_id);
            return err('Plus de places disponibles', 409);
          }

          await syncEventAvailability(env.DB, body.event_id);

          const regData = {
            nom: body.nom, prenom: body.prenom, email: normalizedEmail,
            telephone: body.telephone, date_naissance: body.date_naissance,
            categorie: body.categorie ?? null, niveau: body.niveau ?? null,
            licence_ffk: body.licence_ffk ?? null, message: body.message ?? null,
            is_mineur: body.is_mineur ? 1 : 0,
            parent_nom: body.parent_nom ?? null, parent_prenom: body.parent_prenom ?? null, parent_tel: body.parent_tel ?? null,
            paiement_status: paiementStatus,
          };
          const emailResults = await sendConfirmationEmails(env, { reg: regData, ev });
          return json({
            id: info.meta.last_row_id,
            event_id: body.event_id,
            paiement_status: paiementStatus,
            montant: ev.price,
            emails: emailResults,
          }, 201);
          } 
          
        // PUT /api/registrations/:id/status [admin]
        if (method === 'PUT' && resId && subRes === 'status') {
          await requireAdmin();
          const body = await request.json();
          const validStatuses = ['en_attente', 'paye', 'gratuit', 'annule'];
          if (!validStatuses.includes(body.paiement_status)) {
            return err(`Statut invalide. Valeurs : ${validStatuses.join(', ')}`);
          }
          const registration = await env.DB.prepare(
            `SELECT event_id FROM registrations WHERE id = ?`
          ).bind(resId).first();
          if (!registration) return err('Inscription introuvable', 404);
          const info = await env.DB.prepare(`
            UPDATE registrations SET paiement_status = ?, helloasso_ref = COALESCE(?, helloasso_ref) WHERE id = ?
          `).bind(body.paiement_status, body.helloasso_ref ?? null, resId).run();
          if (info.changes === 0) return err('Inscription introuvable', 404);
          await syncEventAvailability(env.DB, registration.event_id);
          return json({ id: resId, paiement_status: body.paiement_status });
        }

        // DELETE /api/registrations/:id [admin]
        // ── Supprime l'inscription ET restitue une place sur l'événement ──
        if (method === 'DELETE' && resId) {
          await requireAdmin();

          const reg = await env.DB.prepare(
            `SELECT event_id, paiement_status FROM registrations WHERE id = ?`
          ).bind(resId).first();
          if (!reg) return err('Inscription introuvable', 404);

          const info = await env.DB.prepare(
            `DELETE FROM registrations WHERE id = ?`
          ).bind(resId).run();
          if (info.changes === 0) return err('Inscription introuvable', 404);

          await syncEventAvailability(env.DB, reg.event_id);

          return json({ deleted: Number(resId), event_id: reg.event_id });
        }
      }

      // ══════════════════════════════════════════════════════════
      //  CHECKOUT HELLOASSO
      // ══════════════════════════════════════════════════════════
      if (resource === 'checkout' && method === 'POST') {
        const body = await request.json();
        const { event_id, nom, prenom, email } = body;
        if (!event_id || !nom || !prenom || !email) {
          return err('Champs requis : event_id, nom, prenom, email');
        }
        const rawEvent = await env.DB.prepare('SELECT * FROM events WHERE id = ?').bind(event_id).first();
        const ev = rawEvent ? await hydrateEvent(env.DB, rawEvent) : null;
        if (!ev)                     return err('Evenement introuvable', 404);
        if (ev.price === 0)          return err('Evenement gratuit, pas de checkout', 400);
        if (ev.status === 'complet') return err('Evenement complet', 409);
        if (ev.status === 'ferme')   return err('Les inscriptions sont fermées pour cet événement', 409);
        if (ev.spots_left <= 0)      return err('Plus de places disponibles', 409);

        const origin    = url.origin;
        const returnUrl = `${origin}/?checkout=success&event_id=${event_id}`;
        const errorUrl  = `${origin}/?checkout=error&event_id=${event_id}`;

        const redirectUrl = await createHelloAssoCheckout(env, {
          eventTitle: ev.title,
          amount:     ev.price,
          email, prenom, nom,
          returnUrl, errorUrl,
        });
        return json({ redirectUrl });
      }

      return err('Route introuvable', 404);

    } catch (e) {
      if (e instanceof ApiError) return err(e.message, e.status);
      console.error(e);
      return err('Erreur serveur interne', 500);
    }
  },
};
